// AUTO-GENERATED by scripts/generate-photos.ts — curate section
// order/names/colors in the Firestore manifest console, not here.
import type { Collection } from '../types/photos'

export const collections: Collection[] = [
  {"id":"galveston-june-2026","name":"Galveston June 2026","color":"#A4CE8B"},
  {"id":"people","name":"People","color":"#ceaca1"},
  {"id":"birds","name":"Birds","color":"#becea1"},
  {"id":"austin-june-2026","name":"Austin June 2026","color":"#F7E49B"},
  {"id":"buildings","name":"buildings","color":"#a1c0ce"},
  {"id":"bluehole-june-2026","name":"BlueHole June 2026","color":"#86BCBD"},
  {"id":"ft-davis-2026","name":"Ft. Davis 2026","color":"#BA5A5A"},
  {"id":"stars","name":"Stars","color":"#ceaea1"},
  {"id":"landscape","name":"Landscape","color":"#c2a1ce"},
  {"id":"animals","name":"Animals","color":"#ceb8a1"},
]
