// AUTO-GENERATED by scripts/generate-photos.ts — curate names/colors/order
// in collections.overrides.json, not here.
import type { Collection } from '../types/photos'

export const collections: Collection[] = [
  {"id":"this-is-a-keyword","name":"THIS IS A KEYWORD","color":"#cec6a1"},
  {"id":"this-is-another","name":"THIS IS ANOTHER","color":"#a8cea1"},
  {"id":"uncategorized","name":"uncategorized","color":"#cea8a1"},
]
