// AUTO-GENERATED by scripts/generate-photos.ts — do not edit by hand
import type { Photo } from '../types/photos'

export const photos: Photo[] = [
  {
    "slug": "dsc02689",
    "collections": [
      "street"
    ],
    "sizeHint": "medium",
    "displaySrc": "/photos/DSC02689.jpg",
    "rawUrl": null,
    "date": "2026-06-08",
    "location": null,
    "exif": {
      "aperture": "f/5.6",
      "shutter": "1s",
      "iso": 100,
      "focalLength": "135mm",
      "camera": "SONY ILCE-6400",
      "lens": "E 18-135mm F3.5-5.6 OSS"
    },
    "edits": null
  },
  {
    "slug": "dsc02731",
    "collections": [
      "street"
    ],
    "sizeHint": "medium",
    "displaySrc": "/photos/DSC02731.jpg",
    "rawUrl": null,
    "date": "2026-06-08",
    "location": null,
    "exif": {
      "aperture": "f/7.1",
      "shutter": "1s",
      "iso": 100,
      "focalLength": "135mm",
      "camera": "SONY ILCE-6400",
      "lens": "E 18-135mm F3.5-5.6 OSS"
    },
    "edits": null
  },
  {
    "slug": "dsc02766",
    "collections": [
      "street"
    ],
    "sizeHint": "medium",
    "displaySrc": "/photos/DSC02766.jpg",
    "rawUrl": null,
    "date": "2026-06-08",
    "location": null,
    "exif": {
      "aperture": "f/5.6",
      "shutter": "1s",
      "iso": 2500,
      "focalLength": "135mm",
      "camera": "SONY ILCE-6400",
      "lens": "E 18-135mm F3.5-5.6 OSS"
    },
    "edits": null
  },
  {
    "slug": "dsc02768",
    "collections": [
      "street"
    ],
    "sizeHint": "medium",
    "displaySrc": "/photos/DSC02768.jpg",
    "rawUrl": null,
    "date": "2026-06-08",
    "location": null,
    "exif": {
      "aperture": "f/5.6",
      "shutter": "1s",
      "iso": 2500,
      "focalLength": "135mm",
      "camera": "SONY ILCE-6400",
      "lens": "E 18-135mm F3.5-5.6 OSS"
    },
    "edits": null
  },
  {
    "slug": "dsc02780",
    "collections": [
      "street"
    ],
    "sizeHint": "medium",
    "displaySrc": "/photos/DSC02780.jpg",
    "rawUrl": null,
    "date": "2026-06-08",
    "location": null,
    "exif": {
      "aperture": "f/7.1",
      "shutter": "1s",
      "iso": 100,
      "focalLength": "35mm",
      "camera": "SONY ILCE-6400",
      "lens": "E 18-135mm F3.5-5.6 OSS"
    },
    "edits": null
  },
  {
    "slug": "dsc02879",
    "collections": [
      "street"
    ],
    "sizeHint": "medium",
    "displaySrc": "/photos/DSC02879.jpg",
    "rawUrl": null,
    "date": "2026-06-08",
    "location": null,
    "exif": {
      "aperture": "f/4.5",
      "shutter": "1s",
      "iso": 1600,
      "focalLength": "38mm",
      "camera": "SONY ILCE-6400",
      "lens": "E 18-135mm F3.5-5.6 OSS"
    },
    "edits": null
  },
  {
    "slug": "dsc02980",
    "collections": [
      "street"
    ],
    "sizeHint": "medium",
    "displaySrc": "/photos/DSC02980.jpg",
    "rawUrl": null,
    "date": "2026-06-08",
    "location": null,
    "exif": {
      "aperture": "f/5.6",
      "shutter": "1s",
      "iso": 100,
      "focalLength": "103mm",
      "camera": "SONY ILCE-6400",
      "lens": "E 18-135mm F3.5-5.6 OSS"
    },
    "edits": null
  },
  {
    "slug": "dsc03013",
    "collections": [
      "street"
    ],
    "sizeHint": "medium",
    "displaySrc": "/photos/DSC03013.jpg",
    "rawUrl": null,
    "date": "2026-06-08",
    "location": null,
    "exif": {
      "aperture": "f/7.1",
      "shutter": "1s",
      "iso": 100,
      "focalLength": "64mm",
      "camera": "SONY ILCE-6400",
      "lens": "E 18-135mm F3.5-5.6 OSS"
    },
    "edits": null
  },
  {
    "slug": "dsc03056",
    "collections": [
      "street"
    ],
    "sizeHint": "medium",
    "displaySrc": "/photos/DSC03056.jpg",
    "rawUrl": null,
    "date": "2026-06-09",
    "location": null,
    "exif": {
      "aperture": "f/8",
      "shutter": "1s",
      "iso": 250,
      "focalLength": "71mm",
      "camera": "SONY ILCE-6400",
      "lens": "E 18-135mm F3.5-5.6 OSS"
    },
    "edits": null
  },
  {
    "slug": "dsc03063",
    "collections": [
      "street"
    ],
    "sizeHint": "medium",
    "displaySrc": "/photos/DSC03063.jpg",
    "rawUrl": null,
    "date": "2026-06-09",
    "location": null,
    "exif": {
      "aperture": "f/8",
      "shutter": "1s",
      "iso": 1250,
      "focalLength": "30mm",
      "camera": "SONY ILCE-6400",
      "lens": "E 18-135mm F3.5-5.6 OSS"
    },
    "edits": null
  },
  {
    "slug": "dsc03080",
    "collections": [
      "street"
    ],
    "sizeHint": "medium",
    "displaySrc": "/photos/DSC03080.jpg",
    "rawUrl": null,
    "date": "2026-06-09",
    "location": null,
    "exif": {
      "aperture": "f/9",
      "shutter": "1s",
      "iso": 5000,
      "focalLength": "22mm",
      "camera": "SONY ILCE-6400",
      "lens": "E 18-135mm F3.5-5.6 OSS"
    },
    "edits": null
  },
  {
    "slug": "dsc03090",
    "collections": [
      "street"
    ],
    "sizeHint": "medium",
    "displaySrc": "/photos/DSC03090.jpg",
    "rawUrl": null,
    "date": "2026-06-09",
    "location": null,
    "exif": {
      "aperture": "f/5",
      "shutter": "1s",
      "iso": 400,
      "focalLength": "27mm",
      "camera": "SONY ILCE-6400",
      "lens": "E 18-135mm F3.5-5.6 OSS"
    },
    "edits": null
  },
  {
    "slug": "dsc03099",
    "collections": [
      "street"
    ],
    "sizeHint": "medium",
    "displaySrc": "/photos/DSC03099.jpg",
    "rawUrl": null,
    "date": "2026-06-09",
    "location": null,
    "exif": {
      "aperture": "f/16",
      "shutter": "1s",
      "iso": 400,
      "focalLength": "53mm",
      "camera": "SONY ILCE-6400",
      "lens": "E 18-135mm F3.5-5.6 OSS"
    },
    "edits": null
  },
  {
    "slug": "dsc03118",
    "collections": [
      "street"
    ],
    "sizeHint": "medium",
    "displaySrc": "/photos/DSC03118.jpg",
    "rawUrl": null,
    "date": "2026-06-09",
    "location": null,
    "exif": {
      "aperture": "f/5.6",
      "shutter": "1s",
      "iso": 51200,
      "focalLength": "135mm",
      "camera": "SONY ILCE-6400",
      "lens": "E 18-135mm F3.5-5.6 OSS"
    },
    "edits": null
  },
  {
    "slug": "dsc03142",
    "collections": [
      "street"
    ],
    "sizeHint": "medium",
    "displaySrc": "/photos/DSC03142.jpg",
    "rawUrl": null,
    "date": "2026-06-09",
    "location": null,
    "exif": {
      "aperture": "f/5.6",
      "shutter": "5s",
      "iso": 4000,
      "focalLength": "18mm",
      "camera": "SONY ILCE-6400",
      "lens": "E 18-135mm F3.5-5.6 OSS"
    },
    "edits": null
  },
  {
    "slug": "dsc03148",
    "collections": [
      "street"
    ],
    "sizeHint": "medium",
    "displaySrc": "/photos/DSC03148.jpg",
    "rawUrl": null,
    "date": "2026-06-09",
    "location": null,
    "exif": {
      "aperture": "f/9",
      "shutter": "20s",
      "iso": 5000,
      "focalLength": "18mm",
      "camera": "SONY ILCE-6400",
      "lens": "E 18-135mm F3.5-5.6 OSS"
    },
    "edits": null
  },
  {
    "slug": "dsc03149",
    "collections": [
      "street"
    ],
    "sizeHint": "medium",
    "displaySrc": "/photos/DSC03149.jpg",
    "rawUrl": null,
    "date": "2026-06-09",
    "location": null,
    "exif": {
      "aperture": "f/9",
      "shutter": "20s",
      "iso": 4000,
      "focalLength": "18mm",
      "camera": "SONY ILCE-6400",
      "lens": "E 18-135mm F3.5-5.6 OSS"
    },
    "edits": null
  },
  {
    "slug": "dsc03156",
    "collections": [
      "street"
    ],
    "sizeHint": "medium",
    "displaySrc": "/photos/DSC03156.jpg",
    "rawUrl": null,
    "date": "2026-06-09",
    "location": null,
    "exif": {
      "aperture": "f/3.5",
      "shutter": "30s",
      "iso": 2500,
      "focalLength": "18mm",
      "camera": "SONY ILCE-6400",
      "lens": "E 18-135mm F3.5-5.6 OSS"
    },
    "edits": null
  },
  {
    "slug": "dsc03165",
    "collections": [
      "street"
    ],
    "sizeHint": "medium",
    "displaySrc": "/photos/DSC03165.jpg",
    "rawUrl": null,
    "date": "2026-06-09",
    "location": null,
    "exif": {
      "aperture": "f/3.5",
      "shutter": "30s",
      "iso": 2500,
      "focalLength": "18mm",
      "camera": "SONY ILCE-6400",
      "lens": "E 18-135mm F3.5-5.6 OSS"
    },
    "edits": null
  },
  {
    "slug": "dsc03170",
    "collections": [
      "street"
    ],
    "sizeHint": "small",
    "displaySrc": "/photos/DSC03170.jpg",
    "rawUrl": null,
    "date": "2026-06-09",
    "location": null,
    "exif": {
      "aperture": "f/3.5",
      "shutter": "30s",
      "iso": 2500,
      "focalLength": "18mm",
      "camera": "SONY ILCE-6400",
      "lens": "E 18-135mm F3.5-5.6 OSS"
    },
    "edits": null
  },
  {
    "slug": "dsc03173",
    "collections": [
      "street"
    ],
    "sizeHint": "small",
    "displaySrc": "/photos/DSC03173.jpg",
    "rawUrl": null,
    "date": "2026-06-09",
    "location": null,
    "exif": {
      "aperture": "f/3.5",
      "shutter": "30s",
      "iso": 2500,
      "focalLength": "18mm",
      "camera": "SONY ILCE-6400",
      "lens": "E 18-135mm F3.5-5.6 OSS"
    },
    "edits": null
  },
  {
    "slug": "dsc03177",
    "collections": [
      "street"
    ],
    "sizeHint": "small",
    "displaySrc": "/photos/DSC03177.jpg",
    "rawUrl": null,
    "date": "2026-06-09",
    "location": null,
    "exif": {
      "aperture": "f/3.5",
      "shutter": "30s",
      "iso": 4000,
      "focalLength": "18mm",
      "camera": "SONY ILCE-6400",
      "lens": "E 18-135mm F3.5-5.6 OSS"
    },
    "edits": null
  },
  {
    "slug": "dsc03180",
    "collections": [
      "street"
    ],
    "sizeHint": "small",
    "displaySrc": "/photos/DSC03180.jpg",
    "rawUrl": null,
    "date": "2026-06-09",
    "location": null,
    "exif": {
      "aperture": "f/3.5",
      "shutter": "30s",
      "iso": 3200,
      "focalLength": "18mm",
      "camera": "SONY ILCE-6400",
      "lens": "E 18-135mm F3.5-5.6 OSS"
    },
    "edits": null
  },
  {
    "slug": "dsc03185",
    "collections": [
      "street"
    ],
    "sizeHint": "medium",
    "displaySrc": "/photos/DSC03185.jpg",
    "rawUrl": null,
    "date": "2026-06-09",
    "location": null,
    "exif": {
      "aperture": "f/3.5",
      "shutter": "30s",
      "iso": 3200,
      "focalLength": "18mm",
      "camera": "SONY ILCE-6400",
      "lens": "E 18-135mm F3.5-5.6 OSS"
    },
    "edits": null
  },
  {
    "slug": "dsc03220",
    "collections": [
      "street"
    ],
    "sizeHint": "medium",
    "displaySrc": "/photos/DSC03220.jpg",
    "rawUrl": null,
    "date": "2026-06-09",
    "location": null,
    "exif": {
      "aperture": "f/5.6",
      "shutter": "1s",
      "iso": 6400,
      "focalLength": "135mm",
      "camera": "SONY ILCE-6400",
      "lens": "E 18-135mm F3.5-5.6 OSS"
    },
    "edits": null
  },
  {
    "slug": "dsc03221",
    "collections": [
      "street"
    ],
    "sizeHint": "medium",
    "displaySrc": "/photos/DSC03221.jpg",
    "rawUrl": null,
    "date": "2026-06-09",
    "location": null,
    "exif": {
      "aperture": "f/5.6",
      "shutter": "1s",
      "iso": 2500,
      "focalLength": "77mm",
      "camera": "SONY ILCE-6400",
      "lens": "E 18-135mm F3.5-5.6 OSS"
    },
    "edits": null
  },
  {
    "slug": "dsc03230",
    "collections": [
      "street"
    ],
    "sizeHint": "medium",
    "displaySrc": "/photos/DSC03230.jpg",
    "rawUrl": null,
    "date": "2026-06-09",
    "location": null,
    "exif": {
      "aperture": "f/5.6",
      "shutter": "1s",
      "iso": 6400,
      "focalLength": "135mm",
      "camera": "SONY ILCE-6400",
      "lens": "E 18-135mm F3.5-5.6 OSS"
    },
    "edits": null
  },
  {
    "slug": "dsc03234",
    "collections": [
      "street"
    ],
    "sizeHint": "medium",
    "displaySrc": "/photos/DSC03234.jpg",
    "rawUrl": null,
    "date": "2026-06-09",
    "location": null,
    "exif": {
      "aperture": "f/14",
      "shutter": "1s",
      "iso": 6400,
      "focalLength": "135mm",
      "camera": "SONY ILCE-6400",
      "lens": "E 18-135mm F3.5-5.6 OSS"
    },
    "edits": null
  },
  {
    "slug": "dsc03243",
    "collections": [
      "street"
    ],
    "sizeHint": "medium",
    "displaySrc": "/photos/DSC03243.jpg",
    "rawUrl": null,
    "date": "2026-06-09",
    "location": null,
    "exif": {
      "aperture": "f/5",
      "shutter": "1s",
      "iso": 1000,
      "focalLength": "51mm",
      "camera": "SONY ILCE-6400",
      "lens": "E 18-135mm F3.5-5.6 OSS"
    },
    "edits": null
  },
  {
    "slug": "dsc03258",
    "collections": [
      "street"
    ],
    "sizeHint": "medium",
    "displaySrc": "/photos/DSC03258.jpg",
    "rawUrl": null,
    "date": "2026-06-09",
    "location": null,
    "exif": {
      "aperture": "f/5.6",
      "shutter": "1s",
      "iso": 250,
      "focalLength": "93mm",
      "camera": "SONY ILCE-6400",
      "lens": "E 18-135mm F3.5-5.6 OSS"
    },
    "edits": null
  },
  {
    "slug": "dsc03274",
    "collections": [
      "street"
    ],
    "sizeHint": "medium",
    "displaySrc": "/photos/DSC03274.jpg",
    "rawUrl": null,
    "date": "2026-06-09",
    "location": null,
    "exif": {
      "aperture": "f/5.6",
      "shutter": "1s",
      "iso": 100,
      "focalLength": "24mm",
      "camera": "SONY ILCE-6400",
      "lens": "E 18-135mm F3.5-5.6 OSS"
    },
    "edits": null
  },
  {
    "slug": "dsc03276-2",
    "collections": [
      "street"
    ],
    "sizeHint": "medium",
    "displaySrc": "/photos/DSC03276-2.jpg",
    "rawUrl": null,
    "date": "2026-06-09",
    "location": null,
    "exif": {
      "aperture": "f/5.6",
      "shutter": "1s",
      "iso": 100,
      "focalLength": "24mm",
      "camera": "SONY ILCE-6400",
      "lens": "E 18-135mm F3.5-5.6 OSS"
    },
    "edits": null
  },
  {
    "slug": "dsc03300",
    "collections": [
      "street"
    ],
    "sizeHint": "small",
    "displaySrc": "/photos/DSC03300.jpg",
    "rawUrl": null,
    "date": "2026-06-09",
    "location": null,
    "exif": {
      "aperture": "f/5",
      "shutter": "1s",
      "iso": 100,
      "focalLength": "43mm",
      "camera": "SONY ILCE-6400",
      "lens": "E 18-135mm F3.5-5.6 OSS"
    },
    "edits": null
  },
  {
    "slug": "dsc03309",
    "collections": [
      "street"
    ],
    "sizeHint": "medium",
    "displaySrc": "/photos/DSC03309.jpg",
    "rawUrl": null,
    "date": "2026-06-09",
    "location": null,
    "exif": {
      "aperture": "f/5.6",
      "shutter": "1s",
      "iso": 160,
      "focalLength": "77mm",
      "camera": "SONY ILCE-6400",
      "lens": "E 18-135mm F3.5-5.6 OSS"
    },
    "edits": null
  },
  {
    "slug": "dsc03333",
    "collections": [
      "street"
    ],
    "sizeHint": "small",
    "displaySrc": "/photos/DSC03333.jpg",
    "rawUrl": null,
    "date": "2026-06-09",
    "location": null,
    "exif": {
      "aperture": "f/11",
      "shutter": "1s",
      "iso": 100,
      "focalLength": "118mm",
      "camera": "SONY ILCE-6400",
      "lens": "E 18-135mm F3.5-5.6 OSS"
    },
    "edits": null
  },
  {
    "slug": "dsc03344",
    "collections": [
      "street"
    ],
    "sizeHint": "medium",
    "displaySrc": "/photos/DSC03344.jpg",
    "rawUrl": null,
    "date": "2026-06-09",
    "location": null,
    "exif": {
      "aperture": "f/5",
      "shutter": "1s",
      "iso": 100,
      "focalLength": "48mm",
      "camera": "SONY ILCE-6400",
      "lens": "E 18-135mm F3.5-5.6 OSS"
    },
    "edits": null
  },
  {
    "slug": "dsc03370",
    "collections": [
      "street"
    ],
    "sizeHint": "medium",
    "displaySrc": "/photos/DSC03370.jpg",
    "rawUrl": null,
    "date": "2026-06-09",
    "location": null,
    "exif": {
      "aperture": "f/5",
      "shutter": "1s",
      "iso": 100,
      "focalLength": "41mm",
      "camera": "SONY ILCE-6400",
      "lens": "E 18-135mm F3.5-5.6 OSS"
    },
    "edits": null
  },
  {
    "slug": "dsc03381",
    "collections": [
      "street"
    ],
    "sizeHint": "medium",
    "displaySrc": "/photos/DSC03381.jpg",
    "rawUrl": null,
    "date": "2026-06-09",
    "location": null,
    "exif": {
      "aperture": "f/5.6",
      "shutter": "1s",
      "iso": 100,
      "focalLength": "35mm",
      "camera": "SONY ILCE-6400",
      "lens": "E 18-135mm F3.5-5.6 OSS"
    },
    "edits": null
  },
  {
    "slug": "dsc03388",
    "collections": [
      "street"
    ],
    "sizeHint": "medium",
    "displaySrc": "/photos/DSC03388.jpg",
    "rawUrl": null,
    "date": "2026-06-09",
    "location": null,
    "exif": {
      "aperture": "f/5.6",
      "shutter": "1s",
      "iso": 100,
      "focalLength": "36mm",
      "camera": "SONY ILCE-6400",
      "lens": "E 18-135mm F3.5-5.6 OSS"
    },
    "edits": null
  },
  {
    "slug": "dsc03393",
    "collections": [
      "street"
    ],
    "sizeHint": "medium",
    "displaySrc": "/photos/DSC03393.jpg",
    "rawUrl": null,
    "date": "2026-06-09",
    "location": null,
    "exif": {
      "aperture": "f/5.6",
      "shutter": "1s",
      "iso": 100,
      "focalLength": "54mm",
      "camera": "SONY ILCE-6400",
      "lens": "E 18-135mm F3.5-5.6 OSS"
    },
    "edits": null
  },
  {
    "slug": "dsc03428",
    "collections": [
      "street"
    ],
    "sizeHint": "medium",
    "displaySrc": "/photos/DSC03428.jpg",
    "rawUrl": null,
    "date": "2026-06-09",
    "location": null,
    "exif": {
      "aperture": "f/5",
      "shutter": "1s",
      "iso": 100,
      "focalLength": "35mm",
      "camera": "SONY ILCE-6400",
      "lens": "E 18-135mm F3.5-5.6 OSS"
    },
    "edits": null
  },
  {
    "slug": "dsc03433",
    "collections": [
      "street"
    ],
    "sizeHint": "medium",
    "displaySrc": "/photos/DSC03433.jpg",
    "rawUrl": null,
    "date": "2026-06-09",
    "location": null,
    "exif": {
      "aperture": "f/5.6",
      "shutter": "1s",
      "iso": 2000,
      "focalLength": "135mm",
      "camera": "SONY ILCE-6400",
      "lens": "E 18-135mm F3.5-5.6 OSS"
    },
    "edits": null
  },
  {
    "slug": "dsc03461",
    "collections": [
      "street"
    ],
    "sizeHint": "medium",
    "displaySrc": "/photos/DSC03461.jpg",
    "rawUrl": null,
    "date": "2026-06-09",
    "location": null,
    "exif": {
      "aperture": "f/13",
      "shutter": "1s",
      "iso": 100,
      "focalLength": "18mm",
      "camera": "SONY ILCE-6400",
      "lens": "E 18-135mm F3.5-5.6 OSS"
    },
    "edits": null
  },
  {
    "slug": "dsc03482",
    "collections": [
      "street"
    ],
    "sizeHint": "medium",
    "displaySrc": "/photos/DSC03482.jpg",
    "rawUrl": null,
    "date": "2026-06-09",
    "location": null,
    "exif": {
      "aperture": "f/11",
      "shutter": "1s",
      "iso": 500,
      "focalLength": "70mm",
      "camera": "SONY ILCE-6400",
      "lens": "E 18-135mm F3.5-5.6 OSS"
    },
    "edits": null
  },
  {
    "slug": "dsc03483",
    "collections": [
      "street"
    ],
    "sizeHint": "medium",
    "displaySrc": "/photos/DSC03483.jpg",
    "rawUrl": null,
    "date": "2026-06-09",
    "location": null,
    "exif": {
      "aperture": "f/5.6",
      "shutter": "1s",
      "iso": 160,
      "focalLength": "67mm",
      "camera": "SONY ILCE-6400",
      "lens": "E 18-135mm F3.5-5.6 OSS"
    },
    "edits": null
  },
  {
    "slug": "dsc03498",
    "collections": [
      "street"
    ],
    "sizeHint": "medium",
    "displaySrc": "/photos/DSC03498.jpg",
    "rawUrl": null,
    "date": "2026-06-09",
    "location": null,
    "exif": {
      "aperture": "f/5",
      "shutter": "1s",
      "iso": 640,
      "focalLength": "50mm",
      "camera": "SONY ILCE-6400",
      "lens": "E 18-135mm F3.5-5.6 OSS"
    },
    "edits": null
  },
  {
    "slug": "dsc03518",
    "collections": [
      "street"
    ],
    "sizeHint": "medium",
    "displaySrc": "/photos/DSC03518.jpg",
    "rawUrl": null,
    "date": "2026-06-09",
    "location": null,
    "exif": {
      "aperture": "f/7.1",
      "shutter": "1s",
      "iso": 100,
      "focalLength": "39mm",
      "camera": "SONY ILCE-6400",
      "lens": "E 18-135mm F3.5-5.6 OSS"
    },
    "edits": null
  },
  {
    "slug": "dsc03526",
    "collections": [
      "street"
    ],
    "sizeHint": "medium",
    "displaySrc": "/photos/DSC03526.jpg",
    "rawUrl": null,
    "date": "2026-06-09",
    "location": null,
    "exif": {
      "aperture": "f/11",
      "shutter": "1s",
      "iso": 100,
      "focalLength": "63mm",
      "camera": "SONY ILCE-6400",
      "lens": "E 18-135mm F3.5-5.6 OSS"
    },
    "edits": null
  },
  {
    "slug": "dsc03595",
    "collections": [
      "street"
    ],
    "sizeHint": "medium",
    "displaySrc": "/photos/DSC03595.jpg",
    "rawUrl": null,
    "date": "2026-06-10",
    "location": null,
    "exif": {
      "aperture": "f/9",
      "shutter": "1s",
      "iso": 12800,
      "focalLength": "53mm",
      "camera": "SONY ILCE-6400",
      "lens": "E 18-135mm F3.5-5.6 OSS"
    },
    "edits": null
  },
  {
    "slug": "dsc03605",
    "collections": [
      "street"
    ],
    "sizeHint": "medium",
    "displaySrc": "/photos/DSC03605.jpg",
    "rawUrl": null,
    "date": "2026-06-10",
    "location": null,
    "exif": {
      "aperture": "f/4.5",
      "shutter": "1s",
      "iso": 12800,
      "focalLength": "32mm",
      "camera": "SONY ILCE-6400",
      "lens": "E 18-135mm F3.5-5.6 OSS"
    },
    "edits": {
      "Exposure2012": 0.78,
      "Contrast2012": 9,
      "Highlights2012": 19,
      "Shadows2012": 1,
      "Whites2012": 24,
      "Blacks2012": -3,
      "Vibrance": 32,
      "Saturation": 10,
      "Sharpness": 40
    }
  },
  {
    "slug": "dsc03606",
    "collections": [
      "street"
    ],
    "sizeHint": "medium",
    "displaySrc": "/photos/DSC03606.jpg",
    "rawUrl": null,
    "date": "2026-06-10",
    "location": null,
    "exif": {
      "aperture": "f/3.5",
      "shutter": "1s",
      "iso": 12800,
      "focalLength": "18mm",
      "camera": "SONY ILCE-6400",
      "lens": "E 18-135mm F3.5-5.6 OSS"
    },
    "edits": null
  },
  {
    "slug": "dsc03608",
    "collections": [
      "street"
    ],
    "sizeHint": "medium",
    "displaySrc": "/photos/DSC03608.jpg",
    "rawUrl": null,
    "date": "2026-06-10",
    "location": null,
    "exif": {
      "aperture": "f/5",
      "shutter": "1s",
      "iso": 12800,
      "focalLength": "53mm",
      "camera": "SONY ILCE-6400",
      "lens": "E 18-135mm F3.5-5.6 OSS"
    },
    "edits": null
  },
  {
    "slug": "dsc03612",
    "collections": [
      "street"
    ],
    "sizeHint": "small",
    "displaySrc": "/photos/DSC03612.jpg",
    "rawUrl": null,
    "date": "2026-06-10",
    "location": null,
    "exif": {
      "aperture": "f/5.6",
      "shutter": "1s",
      "iso": 12800,
      "focalLength": "69mm",
      "camera": "SONY ILCE-6400",
      "lens": "E 18-135mm F3.5-5.6 OSS"
    },
    "edits": {
      "Exposure2012": 1.35,
      "Contrast2012": 15,
      "Highlights2012": -19,
      "Whites2012": 33,
      "Blacks2012": 4,
      "Sharpness": 40
    }
  },
  {
    "slug": "dsc03640",
    "collections": [
      "street"
    ],
    "sizeHint": "medium",
    "displaySrc": "/photos/DSC03640.jpg",
    "rawUrl": null,
    "date": "2026-06-10",
    "location": null,
    "exif": {
      "aperture": "f/22",
      "shutter": "20s",
      "iso": 5000,
      "focalLength": "40mm",
      "camera": "SONY ILCE-6400",
      "lens": "E 18-135mm F3.5-5.6 OSS"
    },
    "edits": null
  },
  {
    "slug": "dsc03650",
    "collections": [
      "street"
    ],
    "sizeHint": "medium",
    "displaySrc": "/photos/DSC03650.jpg",
    "rawUrl": null,
    "date": "2026-06-10",
    "location": null,
    "exif": {
      "aperture": "f/5",
      "shutter": "30s",
      "iso": 12800,
      "focalLength": "18mm",
      "camera": "SONY ILCE-6400",
      "lens": "E 18-135mm F3.5-5.6 OSS"
    },
    "edits": null
  },
  {
    "slug": "dsc03666",
    "collections": [
      "street"
    ],
    "sizeHint": "small",
    "displaySrc": "/photos/DSC03666.jpg",
    "rawUrl": null,
    "date": "2026-06-10",
    "location": null,
    "exif": {
      "aperture": "f/3.5",
      "shutter": "30s",
      "iso": 12800,
      "focalLength": "18mm",
      "camera": "SONY ILCE-6400",
      "lens": "E 18-135mm F3.5-5.6 OSS"
    },
    "edits": {
      "Exposure2012": 0.19,
      "Contrast2012": 32,
      "Highlights2012": -33,
      "Whites2012": 53,
      "Sharpness": 40,
      "ColorNoiseReduction": 25
    }
  },
  {
    "slug": "dsc03740",
    "collections": [
      "street"
    ],
    "sizeHint": "medium",
    "displaySrc": "/photos/DSC03740.jpg",
    "rawUrl": null,
    "date": "2026-06-12",
    "location": null,
    "exif": {
      "aperture": "f/5",
      "shutter": "1s",
      "iso": 100,
      "focalLength": "45mm",
      "camera": "SONY ILCE-6400",
      "lens": "E 18-135mm F3.5-5.6 OSS"
    },
    "edits": null
  },
  {
    "slug": "dsc03742",
    "collections": [
      "street"
    ],
    "sizeHint": "medium",
    "displaySrc": "/photos/DSC03742.jpg",
    "rawUrl": null,
    "date": "2026-06-12",
    "location": null,
    "exif": {
      "aperture": "f/5",
      "shutter": "1s",
      "iso": 100,
      "focalLength": "45mm",
      "camera": "SONY ILCE-6400",
      "lens": "E 18-135mm F3.5-5.6 OSS"
    },
    "edits": null
  },
  {
    "slug": "dsc03762",
    "collections": [
      "street"
    ],
    "sizeHint": "medium",
    "displaySrc": "/photos/DSC03762.jpg",
    "rawUrl": null,
    "date": "2026-06-12",
    "location": null,
    "exif": {
      "aperture": "f/22",
      "shutter": "1s",
      "iso": 12800,
      "focalLength": "135mm",
      "camera": "SONY ILCE-6400",
      "lens": "E 18-135mm F3.5-5.6 OSS"
    },
    "edits": null
  },
  {
    "slug": "dsc03768",
    "collections": [
      "street"
    ],
    "sizeHint": "medium",
    "displaySrc": "/photos/DSC03768.jpg",
    "rawUrl": null,
    "date": "2026-06-12",
    "location": null,
    "exif": {
      "aperture": "f/22",
      "shutter": "1s",
      "iso": 6400,
      "focalLength": "88mm",
      "camera": "SONY ILCE-6400",
      "lens": "E 18-135mm F3.5-5.6 OSS"
    },
    "edits": null
  },
  {
    "slug": "dsc03772",
    "collections": [
      "street"
    ],
    "sizeHint": "medium",
    "displaySrc": "/photos/DSC03772.jpg",
    "rawUrl": null,
    "date": "2026-06-12",
    "location": null,
    "exif": {
      "aperture": "f/5.6",
      "shutter": "1s",
      "iso": 400,
      "focalLength": "97mm",
      "camera": "SONY ILCE-6400",
      "lens": "E 18-135mm F3.5-5.6 OSS"
    },
    "edits": null
  },
  {
    "slug": "dsc03775",
    "collections": [
      "street"
    ],
    "sizeHint": "medium",
    "displaySrc": "/photos/DSC03775.jpg",
    "rawUrl": null,
    "date": "2026-06-12",
    "location": null,
    "exif": {
      "aperture": "f/5.6",
      "shutter": "1s",
      "iso": 320,
      "focalLength": "56mm",
      "camera": "SONY ILCE-6400",
      "lens": "E 18-135mm F3.5-5.6 OSS"
    },
    "edits": null
  },
  {
    "slug": "dsc03801",
    "collections": [
      "street"
    ],
    "sizeHint": "medium",
    "displaySrc": "/photos/DSC03801.jpg",
    "rawUrl": null,
    "date": "2026-06-12",
    "location": null,
    "exif": {
      "aperture": "f/4.5",
      "shutter": "1s",
      "iso": 250,
      "focalLength": "31mm",
      "camera": "SONY ILCE-6400",
      "lens": "E 18-135mm F3.5-5.6 OSS"
    },
    "edits": null
  },
  {
    "slug": "dsc03829",
    "collections": [
      "street"
    ],
    "sizeHint": "medium",
    "displaySrc": "/photos/DSC03829.jpg",
    "rawUrl": null,
    "date": "2026-06-16",
    "location": null,
    "exif": {
      "aperture": "f/4.5",
      "shutter": "1s",
      "iso": 100,
      "focalLength": "27mm",
      "camera": "SONY ILCE-6400",
      "lens": "E 18-135mm F3.5-5.6 OSS"
    },
    "edits": null
  },
  {
    "slug": "dsc03839",
    "collections": [
      "street"
    ],
    "sizeHint": "medium",
    "displaySrc": "/photos/DSC03839.jpg",
    "rawUrl": null,
    "date": "2026-06-16",
    "location": null,
    "exif": {
      "aperture": "f/14",
      "shutter": "1s",
      "iso": 12800,
      "focalLength": "60mm",
      "camera": "SONY ILCE-6400",
      "lens": "E 18-135mm F3.5-5.6 OSS"
    },
    "edits": null
  },
  {
    "slug": "dsc03846",
    "collections": [
      "street"
    ],
    "sizeHint": "medium",
    "displaySrc": "/photos/DSC03846.jpg",
    "rawUrl": null,
    "date": "2026-06-16",
    "location": null,
    "exif": {
      "aperture": "f/5",
      "shutter": "1s",
      "iso": 1000,
      "focalLength": "53mm",
      "camera": "SONY ILCE-6400",
      "lens": "E 18-135mm F3.5-5.6 OSS"
    },
    "edits": null
  },
  {
    "slug": "dsc03847",
    "collections": [
      "street"
    ],
    "sizeHint": "medium",
    "displaySrc": "/photos/DSC03847.jpg",
    "rawUrl": null,
    "date": "2026-06-16",
    "location": null,
    "exif": {
      "aperture": "f/5",
      "shutter": "1s",
      "iso": 12800,
      "focalLength": "50mm",
      "camera": "SONY ILCE-6400",
      "lens": "E 18-135mm F3.5-5.6 OSS"
    },
    "edits": null
  },
  {
    "slug": "dsc03850",
    "collections": [
      "street"
    ],
    "sizeHint": "medium",
    "displaySrc": "/photos/DSC03850.jpg",
    "rawUrl": null,
    "date": "2026-06-16",
    "location": null,
    "exif": {
      "aperture": "f/5",
      "shutter": "1s",
      "iso": 5000,
      "focalLength": "43mm",
      "camera": "SONY ILCE-6400",
      "lens": "E 18-135mm F3.5-5.6 OSS"
    },
    "edits": null
  },
  {
    "slug": "dsc03855",
    "collections": [
      "street"
    ],
    "sizeHint": "medium",
    "displaySrc": "/photos/DSC03855.jpg",
    "rawUrl": null,
    "date": "2026-06-16",
    "location": null,
    "exif": {
      "aperture": "f/5.6",
      "shutter": "1s",
      "iso": 2000,
      "focalLength": "64mm",
      "camera": "SONY ILCE-6400",
      "lens": "E 18-135mm F3.5-5.6 OSS"
    },
    "edits": null
  },
  {
    "slug": "dsc03859",
    "collections": [
      "street"
    ],
    "sizeHint": "small",
    "displaySrc": "/photos/DSC03859.jpg",
    "rawUrl": null,
    "date": "2026-06-16",
    "location": null,
    "exif": {
      "aperture": "f/5.6",
      "shutter": "1s",
      "iso": 1250,
      "focalLength": "61mm",
      "camera": "SONY ILCE-6400",
      "lens": "E 18-135mm F3.5-5.6 OSS"
    },
    "edits": null
  },
  {
    "slug": "dsc03860",
    "collections": [
      "street"
    ],
    "sizeHint": "medium",
    "displaySrc": "/photos/DSC03860.jpg",
    "rawUrl": null,
    "date": "2026-06-16",
    "location": null,
    "exif": {
      "aperture": "f/5",
      "shutter": "1s",
      "iso": 12800,
      "focalLength": "50mm",
      "camera": "SONY ILCE-6400",
      "lens": "E 18-135mm F3.5-5.6 OSS"
    },
    "edits": null
  },
  {
    "slug": "dsc03865",
    "collections": [
      "street"
    ],
    "sizeHint": "medium",
    "displaySrc": "/photos/DSC03865.jpg",
    "rawUrl": null,
    "date": "2026-06-16",
    "location": null,
    "exif": {
      "aperture": "f/5.6",
      "shutter": "1s",
      "iso": 12800,
      "focalLength": "66mm",
      "camera": "SONY ILCE-6400",
      "lens": "E 18-135mm F3.5-5.6 OSS"
    },
    "edits": null
  },
]
