// AUTO-GENERATED by scripts/generate-photos.ts — do not edit by hand
import type { Photo } from '../types/photos'

export const photos: Photo[] = [
  {
    "slug": "dsc02689",
    "collections": [
      "ft-davis-2026"
    ],
    "sizeHint": "medium",
    "thumbSrc": "/thumbs/dsc02689.webp",
    "displaySrc": "/display/dsc02689.webp",
    "fullSrc": "/photos/DSC02689.jpg",
    "rawUrl": "https://firebasestorage.googleapis.com/v0/b/benwilcoxdev.firebasestorage.app/o/raw%2FDSC02689.ARW?alt=media&token=cc084336-db03-42b2-9923-92e932f8a0c4",
    "date": "2026-06-08",
    "location": null,
    "title": null,
    "caption": null,
    "rating": 5,
    "exif": {
      "aperture": "f/5.6",
      "shutter": "1s",
      "iso": 100,
      "focalLength": "135mm",
      "camera": "SONY ILCE-6400",
      "lens": "E 18-135mm F3.5-5.6 OSS"
    },
    "edits": {
      "Shadows2012": 50,
      "Sharpness": 40,
      "ColorNoiseReduction": 25
    }
  },
  {
    "slug": "dsc02731",
    "collections": [
      "ft-davis-2026"
    ],
    "sizeHint": "medium",
    "thumbSrc": "/thumbs/dsc02731.webp",
    "displaySrc": "/display/dsc02731.webp",
    "fullSrc": "/photos/DSC02731.jpg",
    "rawUrl": "https://firebasestorage.googleapis.com/v0/b/benwilcoxdev.firebasestorage.app/o/raw%2FDSC02731.ARW?alt=media&token=980a8fa2-2c7e-4072-b5b0-3b832ea0ae50",
    "date": "2026-06-08",
    "location": null,
    "title": null,
    "caption": null,
    "rating": 5,
    "exif": {
      "aperture": "f/7.1",
      "shutter": "1s",
      "iso": 100,
      "focalLength": "135mm",
      "camera": "SONY ILCE-6400",
      "lens": "E 18-135mm F3.5-5.6 OSS"
    },
    "edits": {
      "Contrast2012": 25,
      "Sharpness": 40,
      "ColorNoiseReduction": 25
    }
  },
  {
    "slug": "dsc02766",
    "collections": [
      "ft-davis-2026"
    ],
    "sizeHint": "medium",
    "thumbSrc": "/thumbs/dsc02766.webp",
    "displaySrc": "/display/dsc02766.webp",
    "fullSrc": "/photos/DSC02766.jpg",
    "rawUrl": "https://firebasestorage.googleapis.com/v0/b/benwilcoxdev.firebasestorage.app/o/raw%2FDSC02766.ARW?alt=media&token=54bfa195-d3e2-48bd-a0a4-ff0fe4e44f42",
    "date": "2026-06-08",
    "location": null,
    "title": null,
    "caption": null,
    "rating": 4,
    "exif": {
      "aperture": "f/5.6",
      "shutter": "1s",
      "iso": 2500,
      "focalLength": "135mm",
      "camera": "SONY ILCE-6400",
      "lens": "E 18-135mm F3.5-5.6 OSS"
    },
    "edits": {}
  },
  {
    "slug": "dsc02768",
    "collections": [
      "ft-davis-2026"
    ],
    "sizeHint": "medium",
    "thumbSrc": "/thumbs/dsc02768.webp",
    "displaySrc": "/display/dsc02768.webp",
    "fullSrc": "/photos/DSC02768.jpg",
    "rawUrl": "https://firebasestorage.googleapis.com/v0/b/benwilcoxdev.firebasestorage.app/o/raw%2FDSC02768.ARW?alt=media&token=5fc8e5fb-234f-445c-bf86-9bfafcbf8f99",
    "date": "2026-06-08",
    "location": null,
    "title": null,
    "caption": null,
    "rating": 5,
    "exif": {
      "aperture": "f/5.6",
      "shutter": "1s",
      "iso": 2500,
      "focalLength": "135mm",
      "camera": "SONY ILCE-6400",
      "lens": "E 18-135mm F3.5-5.6 OSS"
    },
    "edits": {
      "Contrast2012": 15,
      "Highlights2012": -33,
      "Sharpness": 40,
      "ColorNoiseReduction": 25
    }
  },
  {
    "slug": "dsc02780",
    "collections": [
      "ft-davis-2026"
    ],
    "sizeHint": "medium",
    "thumbSrc": "/thumbs/dsc02780.webp",
    "displaySrc": "/display/dsc02780.webp",
    "fullSrc": "/photos/DSC02780.jpg",
    "rawUrl": "https://firebasestorage.googleapis.com/v0/b/benwilcoxdev.firebasestorage.app/o/raw%2FDSC02780.ARW?alt=media&token=df80a099-2cfa-45a7-928f-e63f5fa63be8",
    "date": "2026-06-08",
    "location": null,
    "title": null,
    "caption": null,
    "rating": 4,
    "exif": {
      "aperture": "f/7.1",
      "shutter": "1s",
      "iso": 100,
      "focalLength": "35mm",
      "camera": "SONY ILCE-6400",
      "lens": "E 18-135mm F3.5-5.6 OSS"
    },
    "edits": {}
  },
  {
    "slug": "dsc02879",
    "collections": [
      "ft-davis-2026"
    ],
    "sizeHint": "medium",
    "thumbSrc": "/thumbs/dsc02879.webp",
    "displaySrc": "/display/dsc02879.webp",
    "fullSrc": "/photos/DSC02879.jpg",
    "rawUrl": "https://firebasestorage.googleapis.com/v0/b/benwilcoxdev.firebasestorage.app/o/raw%2FDSC02879.ARW?alt=media&token=695f92cc-5ae1-4527-85d5-0ae9ca9b61c2",
    "date": "2026-06-08",
    "location": null,
    "title": null,
    "caption": null,
    "rating": 5,
    "exif": {
      "aperture": "f/4.5",
      "shutter": "1s",
      "iso": 1600,
      "focalLength": "38mm",
      "camera": "SONY ILCE-6400",
      "lens": "E 18-135mm F3.5-5.6 OSS"
    },
    "edits": {
      "Exposure2012": -0.12,
      "Highlights2012": -34,
      "Whites2012": -77,
      "Blacks2012": -20,
      "Sharpness": 40,
      "ColorNoiseReduction": 25
    }
  },
  {
    "slug": "dsc02980",
    "collections": [
      "ft-davis-2026"
    ],
    "sizeHint": "medium",
    "thumbSrc": "/thumbs/dsc02980.webp",
    "displaySrc": "/display/dsc02980.webp",
    "fullSrc": "/photos/DSC02980.jpg",
    "rawUrl": "https://firebasestorage.googleapis.com/v0/b/benwilcoxdev.firebasestorage.app/o/raw%2FDSC02980.ARW?alt=media&token=d85c6ea2-afa9-438b-b5c9-8bf5ff98bba2",
    "date": "2026-06-08",
    "location": null,
    "title": null,
    "caption": null,
    "rating": 4,
    "exif": {
      "aperture": "f/5.6",
      "shutter": "1s",
      "iso": 100,
      "focalLength": "103mm",
      "camera": "SONY ILCE-6400",
      "lens": "E 18-135mm F3.5-5.6 OSS"
    },
    "edits": {
      "Sharpness": 40,
      "ColorNoiseReduction": 25
    }
  },
  {
    "slug": "dsc03013",
    "collections": [
      "ft-davis-2026"
    ],
    "sizeHint": "medium",
    "thumbSrc": "/thumbs/dsc03013.webp",
    "displaySrc": "/display/dsc03013.webp",
    "fullSrc": "/photos/DSC03013.jpg",
    "rawUrl": "https://firebasestorage.googleapis.com/v0/b/benwilcoxdev.firebasestorage.app/o/raw%2FDSC03013.ARW?alt=media&token=a38f99ba-282c-4333-8705-c59b113e5b02",
    "date": "2026-06-08",
    "location": null,
    "title": null,
    "caption": null,
    "rating": 4,
    "exif": {
      "aperture": "f/7.1",
      "shutter": "1s",
      "iso": 100,
      "focalLength": "64mm",
      "camera": "SONY ILCE-6400",
      "lens": "E 18-135mm F3.5-5.6 OSS"
    },
    "edits": {}
  },
  {
    "slug": "dsc03056",
    "collections": [
      "ft-davis-2026"
    ],
    "sizeHint": "medium",
    "thumbSrc": "/thumbs/dsc03056.webp",
    "displaySrc": "/display/dsc03056.webp",
    "fullSrc": "/photos/DSC03056.jpg",
    "rawUrl": "https://firebasestorage.googleapis.com/v0/b/benwilcoxdev.firebasestorage.app/o/raw%2FDSC03056.ARW?alt=media&token=8f9b55dd-00c7-4861-8d53-0e20f0c8cc54",
    "date": "2026-06-09",
    "location": null,
    "title": null,
    "caption": null,
    "rating": 5,
    "exif": {
      "aperture": "f/8",
      "shutter": "1s",
      "iso": 250,
      "focalLength": "71mm",
      "camera": "SONY ILCE-6400",
      "lens": "E 18-135mm F3.5-5.6 OSS"
    },
    "edits": {
      "Vibrance": 21,
      "Saturation": 17,
      "Sharpness": 40,
      "ColorNoiseReduction": 25
    }
  },
  {
    "slug": "dsc03063",
    "collections": [
      "ft-davis-2026"
    ],
    "sizeHint": "medium",
    "thumbSrc": "/thumbs/dsc03063.webp",
    "displaySrc": "/display/dsc03063.webp",
    "fullSrc": "/photos/DSC03063.jpg",
    "rawUrl": "https://firebasestorage.googleapis.com/v0/b/benwilcoxdev.firebasestorage.app/o/raw%2FDSC03063.ARW?alt=media&token=0a2dbafb-a82e-4f18-84fa-07b0be9ca364",
    "date": "2026-06-09",
    "location": null,
    "title": null,
    "caption": null,
    "rating": 4,
    "exif": {
      "aperture": "f/8",
      "shutter": "1s",
      "iso": 1250,
      "focalLength": "30mm",
      "camera": "SONY ILCE-6400",
      "lens": "E 18-135mm F3.5-5.6 OSS"
    },
    "edits": {
      "Exposure2012": -0.49,
      "Contrast2012": 20,
      "Highlights2012": -56,
      "Shadows2012": -13,
      "Blacks2012": -27,
      "Vibrance": -23,
      "Saturation": -8,
      "Sharpness": 40,
      "ColorNoiseReduction": 25
    }
  },
  {
    "slug": "dsc03080",
    "collections": [
      "ft-davis-2026"
    ],
    "sizeHint": "medium",
    "thumbSrc": "/thumbs/dsc03080.webp",
    "displaySrc": "/display/dsc03080.webp",
    "fullSrc": "/photos/DSC03080.jpg",
    "rawUrl": "https://firebasestorage.googleapis.com/v0/b/benwilcoxdev.firebasestorage.app/o/raw%2FDSC03080.ARW?alt=media&token=108a9b09-2908-4044-819e-738a6074bbc1",
    "date": "2026-06-09",
    "location": null,
    "title": null,
    "caption": null,
    "rating": 3,
    "exif": {
      "aperture": "f/9",
      "shutter": "1s",
      "iso": 5000,
      "focalLength": "22mm",
      "camera": "SONY ILCE-6400",
      "lens": "E 18-135mm F3.5-5.6 OSS"
    },
    "edits": {
      "Contrast2012": -19,
      "Highlights2012": -39,
      "Shadows2012": 21,
      "Blacks2012": 32,
      "Sharpness": 40,
      "ColorNoiseReduction": 25
    }
  },
  {
    "slug": "dsc03090",
    "collections": [
      "ft-davis-2026"
    ],
    "sizeHint": "medium",
    "thumbSrc": "/thumbs/dsc03090.webp",
    "displaySrc": "/display/dsc03090.webp",
    "fullSrc": "/photos/DSC03090.jpg",
    "rawUrl": "https://firebasestorage.googleapis.com/v0/b/benwilcoxdev.firebasestorage.app/o/raw%2FDSC03090.ARW?alt=media&token=a2b3a349-2ad1-4269-aa56-a3d4f74c7807",
    "date": "2026-06-09",
    "location": null,
    "title": null,
    "caption": null,
    "rating": 4,
    "exif": {
      "aperture": "f/5",
      "shutter": "1s",
      "iso": 400,
      "focalLength": "27mm",
      "camera": "SONY ILCE-6400",
      "lens": "E 18-135mm F3.5-5.6 OSS"
    },
    "edits": {
      "Saturation": 11,
      "Sharpness": 40,
      "ColorNoiseReduction": 25
    }
  },
  {
    "slug": "dsc03099",
    "collections": [
      "ft-davis-2026"
    ],
    "sizeHint": "medium",
    "thumbSrc": "/thumbs/dsc03099.webp",
    "displaySrc": "/display/dsc03099.webp",
    "fullSrc": "/photos/DSC03099.jpg",
    "rawUrl": "https://firebasestorage.googleapis.com/v0/b/benwilcoxdev.firebasestorage.app/o/raw%2FDSC03099.ARW?alt=media&token=5d6e4784-5522-4b5f-9a22-6312c46b230f",
    "date": "2026-06-09",
    "location": null,
    "title": null,
    "caption": null,
    "rating": 4,
    "exif": {
      "aperture": "f/16",
      "shutter": "1s",
      "iso": 400,
      "focalLength": "53mm",
      "camera": "SONY ILCE-6400",
      "lens": "E 18-135mm F3.5-5.6 OSS"
    },
    "edits": {
      "Clarity2012": 17,
      "Vibrance": 10,
      "Sharpness": 40,
      "ColorNoiseReduction": 25
    }
  },
  {
    "slug": "dsc03118",
    "collections": [
      "ft-davis-2026"
    ],
    "sizeHint": "medium",
    "thumbSrc": "/thumbs/dsc03118.webp",
    "displaySrc": "/display/dsc03118.webp",
    "fullSrc": "/photos/DSC03118.jpg",
    "rawUrl": "https://firebasestorage.googleapis.com/v0/b/benwilcoxdev.firebasestorage.app/o/raw%2FDSC03118.ARW?alt=media&token=58948f2a-6b15-4a64-8caf-dd5f00692a02",
    "date": "2026-06-09",
    "location": null,
    "title": null,
    "caption": null,
    "rating": 4,
    "exif": {
      "aperture": "f/5.6",
      "shutter": "1s",
      "iso": 51200,
      "focalLength": "135mm",
      "camera": "SONY ILCE-6400",
      "lens": "E 18-135mm F3.5-5.6 OSS"
    },
    "edits": {
      "Exposure2012": 0.09,
      "Contrast2012": 14,
      "Vibrance": 21,
      "Saturation": 16,
      "Sharpness": 40
    }
  },
  {
    "slug": "dsc03142",
    "collections": [
      "ft-davis-2026"
    ],
    "sizeHint": "medium",
    "thumbSrc": "/thumbs/dsc03142.webp",
    "displaySrc": "/display/dsc03142.webp",
    "fullSrc": "/photos/DSC03142.jpg",
    "rawUrl": "https://firebasestorage.googleapis.com/v0/b/benwilcoxdev.firebasestorage.app/o/raw%2FDSC03142.ARW?alt=media&token=1eb6ffab-1cf8-4e6e-9935-55f9b961314e",
    "date": "2026-06-09",
    "location": null,
    "title": null,
    "caption": null,
    "rating": 4,
    "exif": {
      "aperture": "f/5.6",
      "shutter": "5s",
      "iso": 4000,
      "focalLength": "18mm",
      "camera": "SONY ILCE-6400",
      "lens": "E 18-135mm F3.5-5.6 OSS"
    },
    "edits": {
      "Contrast2012": 37,
      "Vibrance": 27,
      "Sharpness": 40,
      "ColorNoiseReduction": 25
    }
  },
  {
    "slug": "dsc03148",
    "collections": [
      "ft-davis-2026"
    ],
    "sizeHint": "medium",
    "thumbSrc": "/thumbs/dsc03148.webp",
    "displaySrc": "/display/dsc03148.webp",
    "fullSrc": "/photos/DSC03148.jpg",
    "rawUrl": "https://firebasestorage.googleapis.com/v0/b/benwilcoxdev.firebasestorage.app/o/raw%2FDSC03148.ARW?alt=media&token=fd35171b-81a3-4d6d-bde8-362c39d21846",
    "date": "2026-06-09",
    "location": null,
    "title": null,
    "caption": null,
    "rating": 4,
    "exif": {
      "aperture": "f/9",
      "shutter": "20s",
      "iso": 5000,
      "focalLength": "18mm",
      "camera": "SONY ILCE-6400",
      "lens": "E 18-135mm F3.5-5.6 OSS"
    },
    "edits": {
      "Sharpness": 40,
      "ColorNoiseReduction": 25
    }
  },
  {
    "slug": "dsc03149",
    "collections": [
      "ft-davis-2026"
    ],
    "sizeHint": "medium",
    "thumbSrc": "/thumbs/dsc03149.webp",
    "displaySrc": "/display/dsc03149.webp",
    "fullSrc": "/photos/DSC03149.jpg",
    "rawUrl": "https://firebasestorage.googleapis.com/v0/b/benwilcoxdev.firebasestorage.app/o/raw%2FDSC03149.ARW?alt=media&token=8a09e0b4-6fe7-4435-9b77-00f8387a7c3b",
    "date": "2026-06-09",
    "location": null,
    "title": null,
    "caption": null,
    "rating": 5,
    "exif": {
      "aperture": "f/9",
      "shutter": "20s",
      "iso": 4000,
      "focalLength": "18mm",
      "camera": "SONY ILCE-6400",
      "lens": "E 18-135mm F3.5-5.6 OSS"
    },
    "edits": {
      "Exposure2012": 0.44,
      "Contrast2012": 35,
      "Sharpness": 40,
      "ColorNoiseReduction": 25
    }
  },
  {
    "slug": "dsc03156",
    "collections": [
      "ft-davis-2026"
    ],
    "sizeHint": "medium",
    "thumbSrc": "/thumbs/dsc03156.webp",
    "displaySrc": "/display/dsc03156.webp",
    "fullSrc": "/photos/DSC03156.jpg",
    "rawUrl": "https://firebasestorage.googleapis.com/v0/b/benwilcoxdev.firebasestorage.app/o/raw%2FDSC03156.ARW?alt=media&token=fe2f33cc-9052-4062-b0c3-0cafc1367a49",
    "date": "2026-06-09",
    "location": null,
    "title": null,
    "caption": null,
    "rating": 4,
    "exif": {
      "aperture": "f/3.5",
      "shutter": "30s",
      "iso": 2500,
      "focalLength": "18mm",
      "camera": "SONY ILCE-6400",
      "lens": "E 18-135mm F3.5-5.6 OSS"
    },
    "edits": {}
  },
  {
    "slug": "dsc03165",
    "collections": [
      "ft-davis-2026"
    ],
    "sizeHint": "medium",
    "thumbSrc": "/thumbs/dsc03165.webp",
    "displaySrc": "/display/dsc03165.webp",
    "fullSrc": "/photos/DSC03165.jpg",
    "rawUrl": "https://firebasestorage.googleapis.com/v0/b/benwilcoxdev.firebasestorage.app/o/raw%2FDSC03165.ARW?alt=media&token=14849462-7a7f-4513-a94f-d6f4b198b7f2",
    "date": "2026-06-09",
    "location": null,
    "title": null,
    "caption": null,
    "rating": 5,
    "exif": {
      "aperture": "f/3.5",
      "shutter": "30s",
      "iso": 2500,
      "focalLength": "18mm",
      "camera": "SONY ILCE-6400",
      "lens": "E 18-135mm F3.5-5.6 OSS"
    },
    "edits": {
      "Exposure2012": 0.34,
      "Contrast2012": 37,
      "Sharpness": 40,
      "ColorNoiseReduction": 25
    }
  },
  {
    "slug": "dsc03170",
    "collections": [
      "ft-davis-2026"
    ],
    "sizeHint": "small",
    "thumbSrc": "/thumbs/dsc03170.webp",
    "displaySrc": "/display/dsc03170.webp",
    "fullSrc": "/photos/DSC03170.jpg",
    "rawUrl": "https://firebasestorage.googleapis.com/v0/b/benwilcoxdev.firebasestorage.app/o/raw%2FDSC03170.ARW?alt=media&token=d944c4f2-7111-45b3-9639-5d3bcc923839",
    "date": "2026-06-09",
    "location": null,
    "title": null,
    "caption": null,
    "rating": 4,
    "exif": {
      "aperture": "f/3.5",
      "shutter": "30s",
      "iso": 2500,
      "focalLength": "18mm",
      "camera": "SONY ILCE-6400",
      "lens": "E 18-135mm F3.5-5.6 OSS"
    },
    "edits": {}
  },
  {
    "slug": "dsc03173",
    "collections": [
      "ft-davis-2026"
    ],
    "sizeHint": "small",
    "thumbSrc": "/thumbs/dsc03173.webp",
    "displaySrc": "/display/dsc03173.webp",
    "fullSrc": "/photos/DSC03173.jpg",
    "rawUrl": "https://firebasestorage.googleapis.com/v0/b/benwilcoxdev.firebasestorage.app/o/raw%2FDSC03173.ARW?alt=media&token=977cd56b-9324-4a20-ad04-b258e5900141",
    "date": "2026-06-09",
    "location": null,
    "title": null,
    "caption": null,
    "rating": 5,
    "exif": {
      "aperture": "f/3.5",
      "shutter": "30s",
      "iso": 2500,
      "focalLength": "18mm",
      "camera": "SONY ILCE-6400",
      "lens": "E 18-135mm F3.5-5.6 OSS"
    },
    "edits": {
      "Exposure2012": 0.33,
      "Contrast2012": 24,
      "Sharpness": 40,
      "ColorNoiseReduction": 25
    }
  },
  {
    "slug": "dsc03177",
    "collections": [
      "ft-davis-2026"
    ],
    "sizeHint": "small",
    "thumbSrc": "/thumbs/dsc03177.webp",
    "displaySrc": "/display/dsc03177.webp",
    "fullSrc": "/photos/DSC03177.jpg",
    "rawUrl": "https://firebasestorage.googleapis.com/v0/b/benwilcoxdev.firebasestorage.app/o/raw%2FDSC03177.ARW?alt=media&token=0c9c2cdc-bcf8-414f-a0d2-d8af9b882779",
    "date": "2026-06-09",
    "location": null,
    "title": null,
    "caption": null,
    "rating": 5,
    "exif": {
      "aperture": "f/3.5",
      "shutter": "30s",
      "iso": 4000,
      "focalLength": "18mm",
      "camera": "SONY ILCE-6400",
      "lens": "E 18-135mm F3.5-5.6 OSS"
    },
    "edits": {
      "Exposure2012": 0.28,
      "Contrast2012": 26,
      "Sharpness": 40,
      "ColorNoiseReduction": 25
    }
  },
  {
    "slug": "dsc03180",
    "collections": [
      "ft-davis-2026"
    ],
    "sizeHint": "small",
    "thumbSrc": "/thumbs/dsc03180.webp",
    "displaySrc": "/display/dsc03180.webp",
    "fullSrc": "/photos/DSC03180.jpg",
    "rawUrl": "https://firebasestorage.googleapis.com/v0/b/benwilcoxdev.firebasestorage.app/o/raw%2FDSC03180.ARW?alt=media&token=9042c25b-c0e4-4a48-a5fd-b99fb92a9b23",
    "date": "2026-06-09",
    "location": null,
    "title": null,
    "caption": null,
    "rating": 5,
    "exif": {
      "aperture": "f/3.5",
      "shutter": "30s",
      "iso": 3200,
      "focalLength": "18mm",
      "camera": "SONY ILCE-6400",
      "lens": "E 18-135mm F3.5-5.6 OSS"
    },
    "edits": {
      "Sharpness": 40,
      "ColorNoiseReduction": 25
    }
  },
  {
    "slug": "dsc03185",
    "collections": [
      "ft-davis-2026"
    ],
    "sizeHint": "medium",
    "thumbSrc": "/thumbs/dsc03185.webp",
    "displaySrc": "/display/dsc03185.webp",
    "fullSrc": "/photos/DSC03185.jpg",
    "rawUrl": "https://firebasestorage.googleapis.com/v0/b/benwilcoxdev.firebasestorage.app/o/raw%2FDSC03185.ARW?alt=media&token=70b026b9-3959-4a23-bb46-4abc235a5010",
    "date": "2026-06-09",
    "location": null,
    "title": null,
    "caption": null,
    "rating": 5,
    "exif": {
      "aperture": "f/3.5",
      "shutter": "30s",
      "iso": 3200,
      "focalLength": "18mm",
      "camera": "SONY ILCE-6400",
      "lens": "E 18-135mm F3.5-5.6 OSS"
    },
    "edits": {
      "Exposure2012": 0.14,
      "Contrast2012": 20,
      "Whites2012": 6,
      "Sharpness": 40,
      "ColorNoiseReduction": 25
    }
  },
  {
    "slug": "dsc03220",
    "collections": [
      "ft-davis-2026"
    ],
    "sizeHint": "medium",
    "thumbSrc": "/thumbs/dsc03220.webp",
    "displaySrc": "/display/dsc03220.webp",
    "fullSrc": "/photos/DSC03220.jpg",
    "rawUrl": "https://firebasestorage.googleapis.com/v0/b/benwilcoxdev.firebasestorage.app/o/raw%2FDSC03220.ARW?alt=media&token=0f822810-14f7-4c49-b39e-ba5325605fac",
    "date": "2026-06-09",
    "location": null,
    "title": null,
    "caption": null,
    "rating": 4,
    "exif": {
      "aperture": "f/5.6",
      "shutter": "1s",
      "iso": 6400,
      "focalLength": "135mm",
      "camera": "SONY ILCE-6400",
      "lens": "E 18-135mm F3.5-5.6 OSS"
    },
    "edits": {}
  },
  {
    "slug": "dsc03221",
    "collections": [
      "ft-davis-2026"
    ],
    "sizeHint": "medium",
    "thumbSrc": "/thumbs/dsc03221.webp",
    "displaySrc": "/display/dsc03221.webp",
    "fullSrc": "/photos/DSC03221.jpg",
    "rawUrl": "https://firebasestorage.googleapis.com/v0/b/benwilcoxdev.firebasestorage.app/o/raw%2FDSC03221.ARW?alt=media&token=c6f935b0-6b1d-4809-bb02-e6641914d400",
    "date": "2026-06-09",
    "location": null,
    "title": null,
    "caption": null,
    "rating": 4,
    "exif": {
      "aperture": "f/5.6",
      "shutter": "1s",
      "iso": 2500,
      "focalLength": "77mm",
      "camera": "SONY ILCE-6400",
      "lens": "E 18-135mm F3.5-5.6 OSS"
    },
    "edits": {
      "Exposure2012": 0.68,
      "Highlights2012": -13,
      "Shadows2012": 13,
      "Whites2012": 19,
      "Blacks2012": 15,
      "Sharpness": 40,
      "ColorNoiseReduction": 25
    }
  },
  {
    "slug": "dsc03230",
    "collections": [
      "ft-davis-2026"
    ],
    "sizeHint": "medium",
    "thumbSrc": "/thumbs/dsc03230.webp",
    "displaySrc": "/display/dsc03230.webp",
    "fullSrc": "/photos/DSC03230.jpg",
    "rawUrl": "https://firebasestorage.googleapis.com/v0/b/benwilcoxdev.firebasestorage.app/o/raw%2FDSC03230.ARW?alt=media&token=164389c5-3eb0-4ff3-8596-ec2279c1a03d",
    "date": "2026-06-09",
    "location": null,
    "title": null,
    "caption": null,
    "rating": 5,
    "exif": {
      "aperture": "f/5.6",
      "shutter": "1s",
      "iso": 6400,
      "focalLength": "135mm",
      "camera": "SONY ILCE-6400",
      "lens": "E 18-135mm F3.5-5.6 OSS"
    },
    "edits": {
      "Sharpness": 40,
      "ColorNoiseReduction": 25
    }
  },
  {
    "slug": "dsc03234",
    "collections": [
      "ft-davis-2026"
    ],
    "sizeHint": "medium",
    "thumbSrc": "/thumbs/dsc03234.webp",
    "displaySrc": "/display/dsc03234.webp",
    "fullSrc": "/photos/DSC03234.jpg",
    "rawUrl": "https://firebasestorage.googleapis.com/v0/b/benwilcoxdev.firebasestorage.app/o/raw%2FDSC03234.ARW?alt=media&token=9e4e9664-5dd7-4860-98d8-83390e4fd972",
    "date": "2026-06-09",
    "location": null,
    "title": null,
    "caption": null,
    "rating": 5,
    "exif": {
      "aperture": "f/14",
      "shutter": "1s",
      "iso": 6400,
      "focalLength": "135mm",
      "camera": "SONY ILCE-6400",
      "lens": "E 18-135mm F3.5-5.6 OSS"
    },
    "edits": {
      "Exposure2012": 1.17,
      "Sharpness": 40,
      "ColorNoiseReduction": 25
    }
  },
  {
    "slug": "dsc03243",
    "collections": [
      "ft-davis-2026"
    ],
    "sizeHint": "medium",
    "thumbSrc": "/thumbs/dsc03243.webp",
    "displaySrc": "/display/dsc03243.webp",
    "fullSrc": "/photos/DSC03243.jpg",
    "rawUrl": "https://firebasestorage.googleapis.com/v0/b/benwilcoxdev.firebasestorage.app/o/raw%2FDSC03243.ARW?alt=media&token=49838c28-0825-4160-9e28-03eb14bea773",
    "date": "2026-06-09",
    "location": null,
    "title": null,
    "caption": null,
    "rating": 5,
    "exif": {
      "aperture": "f/5",
      "shutter": "1s",
      "iso": 1000,
      "focalLength": "51mm",
      "camera": "SONY ILCE-6400",
      "lens": "E 18-135mm F3.5-5.6 OSS"
    },
    "edits": {}
  },
  {
    "slug": "dsc03258",
    "collections": [
      "ft-davis-2026"
    ],
    "sizeHint": "medium",
    "thumbSrc": "/thumbs/dsc03258.webp",
    "displaySrc": "/display/dsc03258.webp",
    "fullSrc": "/photos/DSC03258.jpg",
    "rawUrl": "https://firebasestorage.googleapis.com/v0/b/benwilcoxdev.firebasestorage.app/o/raw%2FDSC03258.ARW?alt=media&token=7b3cbcc7-48d1-47c8-970e-36f150614519",
    "date": "2026-06-09",
    "location": null,
    "title": null,
    "caption": null,
    "rating": 5,
    "exif": {
      "aperture": "f/5.6",
      "shutter": "1s",
      "iso": 250,
      "focalLength": "93mm",
      "camera": "SONY ILCE-6400",
      "lens": "E 18-135mm F3.5-5.6 OSS"
    },
    "edits": {}
  },
  {
    "slug": "dsc03274",
    "collections": [
      "ft-davis-2026"
    ],
    "sizeHint": "medium",
    "thumbSrc": "/thumbs/dsc03274.webp",
    "displaySrc": "/display/dsc03274.webp",
    "fullSrc": "/photos/DSC03274.jpg",
    "rawUrl": "https://firebasestorage.googleapis.com/v0/b/benwilcoxdev.firebasestorage.app/o/raw%2FDSC03274.ARW?alt=media&token=f7215df3-6b1c-4e3b-88a9-379e0689dbfc",
    "date": "2026-06-09",
    "location": null,
    "title": null,
    "caption": null,
    "rating": 5,
    "exif": {
      "aperture": "f/5.6",
      "shutter": "1s",
      "iso": 100,
      "focalLength": "24mm",
      "camera": "SONY ILCE-6400",
      "lens": "E 18-135mm F3.5-5.6 OSS"
    },
    "edits": {}
  },
  {
    "slug": "dsc03276-2",
    "collections": [
      "uncategorized"
    ],
    "sizeHint": "medium",
    "thumbSrc": "/thumbs/dsc03276-2.webp",
    "displaySrc": "/display/dsc03276-2.webp",
    "fullSrc": "/photos/DSC03276-2.jpg",
    "rawUrl": null,
    "date": "2026-06-09",
    "location": null,
    "title": null,
    "caption": null,
    "rating": 5,
    "exif": {
      "aperture": "f/5.6",
      "shutter": "1s",
      "iso": 100,
      "focalLength": "24mm",
      "camera": "SONY ILCE-6400",
      "lens": "E 18-135mm F3.5-5.6 OSS"
    },
    "edits": null
  },
  {
    "slug": "dsc03300",
    "collections": [
      "ft-davis-2026"
    ],
    "sizeHint": "small",
    "thumbSrc": "/thumbs/dsc03300.webp",
    "displaySrc": "/display/dsc03300.webp",
    "fullSrc": "/photos/DSC03300.jpg",
    "rawUrl": "https://firebasestorage.googleapis.com/v0/b/benwilcoxdev.firebasestorage.app/o/raw%2FDSC03300.ARW?alt=media&token=48093475-0c35-46c4-be82-33c13a2b28bb",
    "date": "2026-06-09",
    "location": null,
    "title": null,
    "caption": null,
    "rating": 5,
    "exif": {
      "aperture": "f/5",
      "shutter": "1s",
      "iso": 100,
      "focalLength": "43mm",
      "camera": "SONY ILCE-6400",
      "lens": "E 18-135mm F3.5-5.6 OSS"
    },
    "edits": {}
  },
  {
    "slug": "dsc03309",
    "collections": [
      "ft-davis-2026"
    ],
    "sizeHint": "medium",
    "thumbSrc": "/thumbs/dsc03309.webp",
    "displaySrc": "/display/dsc03309.webp",
    "fullSrc": "/photos/DSC03309.jpg",
    "rawUrl": "https://firebasestorage.googleapis.com/v0/b/benwilcoxdev.firebasestorage.app/o/raw%2FDSC03309.ARW?alt=media&token=3a9f441e-cbd6-4416-a978-497468f8b54a",
    "date": "2026-06-09",
    "location": null,
    "title": null,
    "caption": null,
    "rating": 5,
    "exif": {
      "aperture": "f/5.6",
      "shutter": "1s",
      "iso": 160,
      "focalLength": "77mm",
      "camera": "SONY ILCE-6400",
      "lens": "E 18-135mm F3.5-5.6 OSS"
    },
    "edits": {}
  },
  {
    "slug": "dsc03333",
    "collections": [
      "ft-davis-2026"
    ],
    "sizeHint": "small",
    "thumbSrc": "/thumbs/dsc03333.webp",
    "displaySrc": "/display/dsc03333.webp",
    "fullSrc": "/photos/DSC03333.jpg",
    "rawUrl": "https://firebasestorage.googleapis.com/v0/b/benwilcoxdev.firebasestorage.app/o/raw%2FDSC03333.ARW?alt=media&token=c0502616-4976-4ca5-bb37-5edff5ea2ea9",
    "date": "2026-06-09",
    "location": null,
    "title": null,
    "caption": null,
    "rating": 5,
    "exif": {
      "aperture": "f/11",
      "shutter": "1s",
      "iso": 100,
      "focalLength": "118mm",
      "camera": "SONY ILCE-6400",
      "lens": "E 18-135mm F3.5-5.6 OSS"
    },
    "edits": {}
  },
  {
    "slug": "dsc03344",
    "collections": [
      "ft-davis-2026"
    ],
    "sizeHint": "medium",
    "thumbSrc": "/thumbs/dsc03344.webp",
    "displaySrc": "/display/dsc03344.webp",
    "fullSrc": "/photos/DSC03344.jpg",
    "rawUrl": "https://firebasestorage.googleapis.com/v0/b/benwilcoxdev.firebasestorage.app/o/raw%2FDSC03344.ARW?alt=media&token=befdbeab-0963-4ce6-b9ff-bdf60e5b18a2",
    "date": "2026-06-09",
    "location": null,
    "title": null,
    "caption": null,
    "rating": 5,
    "exif": {
      "aperture": "f/5",
      "shutter": "1s",
      "iso": 100,
      "focalLength": "48mm",
      "camera": "SONY ILCE-6400",
      "lens": "E 18-135mm F3.5-5.6 OSS"
    },
    "edits": {
      "Sharpness": 40,
      "ColorNoiseReduction": 25
    }
  },
  {
    "slug": "dsc03370",
    "collections": [
      "ft-davis-2026"
    ],
    "sizeHint": "medium",
    "thumbSrc": "/thumbs/dsc03370.webp",
    "displaySrc": "/display/dsc03370.webp",
    "fullSrc": "/photos/DSC03370.jpg",
    "rawUrl": "https://firebasestorage.googleapis.com/v0/b/benwilcoxdev.firebasestorage.app/o/raw%2FDSC03370.ARW?alt=media&token=9bbda17b-4e8c-461f-8d92-c97143444e61",
    "date": "2026-06-09",
    "location": null,
    "title": null,
    "caption": null,
    "rating": 5,
    "exif": {
      "aperture": "f/5",
      "shutter": "1s",
      "iso": 100,
      "focalLength": "41mm",
      "camera": "SONY ILCE-6400",
      "lens": "E 18-135mm F3.5-5.6 OSS"
    },
    "edits": {}
  },
  {
    "slug": "dsc03381",
    "collections": [
      "ft-davis-2026"
    ],
    "sizeHint": "medium",
    "thumbSrc": "/thumbs/dsc03381.webp",
    "displaySrc": "/display/dsc03381.webp",
    "fullSrc": "/photos/DSC03381.jpg",
    "rawUrl": "https://firebasestorage.googleapis.com/v0/b/benwilcoxdev.firebasestorage.app/o/raw%2FDSC03381.ARW?alt=media&token=523b99bb-15d6-4474-8001-463285d2d912",
    "date": "2026-06-09",
    "location": null,
    "title": null,
    "caption": null,
    "rating": 5,
    "exif": {
      "aperture": "f/5.6",
      "shutter": "1s",
      "iso": 100,
      "focalLength": "35mm",
      "camera": "SONY ILCE-6400",
      "lens": "E 18-135mm F3.5-5.6 OSS"
    },
    "edits": {
      "Shadows2012": -30,
      "Sharpness": 40,
      "ColorNoiseReduction": 25
    }
  },
  {
    "slug": "dsc03388",
    "collections": [
      "ft-davis-2026"
    ],
    "sizeHint": "medium",
    "thumbSrc": "/thumbs/dsc03388.webp",
    "displaySrc": "/display/dsc03388.webp",
    "fullSrc": "/photos/DSC03388.jpg",
    "rawUrl": "https://firebasestorage.googleapis.com/v0/b/benwilcoxdev.firebasestorage.app/o/raw%2FDSC03388.ARW?alt=media&token=b2731a7b-3d54-4706-9062-1b53369e5387",
    "date": "2026-06-09",
    "location": null,
    "title": null,
    "caption": null,
    "rating": 5,
    "exif": {
      "aperture": "f/5.6",
      "shutter": "1s",
      "iso": 100,
      "focalLength": "36mm",
      "camera": "SONY ILCE-6400",
      "lens": "E 18-135mm F3.5-5.6 OSS"
    },
    "edits": {
      "Exposure2012": 0.28,
      "Contrast2012": 51,
      "Highlights2012": -68,
      "Shadows2012": 51,
      "Blacks2012": 100,
      "Sharpness": 40,
      "ColorNoiseReduction": 25
    }
  },
  {
    "slug": "dsc03393",
    "collections": [
      "ft-davis-2026"
    ],
    "sizeHint": "medium",
    "thumbSrc": "/thumbs/dsc03393.webp",
    "displaySrc": "/display/dsc03393.webp",
    "fullSrc": "/photos/DSC03393.jpg",
    "rawUrl": "https://firebasestorage.googleapis.com/v0/b/benwilcoxdev.firebasestorage.app/o/raw%2FDSC03393.ARW?alt=media&token=2049bd97-5ca6-46c5-9ce8-8c791c4b5913",
    "date": "2026-06-09",
    "location": null,
    "title": null,
    "caption": null,
    "rating": 5,
    "exif": {
      "aperture": "f/5.6",
      "shutter": "1s",
      "iso": 100,
      "focalLength": "54mm",
      "camera": "SONY ILCE-6400",
      "lens": "E 18-135mm F3.5-5.6 OSS"
    },
    "edits": {
      "Exposure2012": 0.92,
      "Contrast2012": 6,
      "Highlights2012": -38,
      "Shadows2012": 79,
      "Whites2012": 15,
      "Blacks2012": -39,
      "Vibrance": 15,
      "Sharpness": 40,
      "ColorNoiseReduction": 25
    }
  },
  {
    "slug": "dsc03428",
    "collections": [
      "ft-davis-2026"
    ],
    "sizeHint": "medium",
    "thumbSrc": "/thumbs/dsc03428.webp",
    "displaySrc": "/display/dsc03428.webp",
    "fullSrc": "/photos/DSC03428.jpg",
    "rawUrl": "https://firebasestorage.googleapis.com/v0/b/benwilcoxdev.firebasestorage.app/o/raw%2FDSC03428.ARW?alt=media&token=73e5d1ff-fea1-4853-bcc1-b1c43dab3d8b",
    "date": "2026-06-09",
    "location": null,
    "title": null,
    "caption": null,
    "rating": 5,
    "exif": {
      "aperture": "f/5",
      "shutter": "1s",
      "iso": 100,
      "focalLength": "35mm",
      "camera": "SONY ILCE-6400",
      "lens": "E 18-135mm F3.5-5.6 OSS"
    },
    "edits": {
      "Highlights2012": -75,
      "Blacks2012": 55,
      "Sharpness": 40,
      "ColorNoiseReduction": 25
    }
  },
  {
    "slug": "dsc03433",
    "collections": [
      "ft-davis-2026"
    ],
    "sizeHint": "medium",
    "thumbSrc": "/thumbs/dsc03433.webp",
    "displaySrc": "/display/dsc03433.webp",
    "fullSrc": "/photos/DSC03433.jpg",
    "rawUrl": "https://firebasestorage.googleapis.com/v0/b/benwilcoxdev.firebasestorage.app/o/raw%2FDSC03433.ARW?alt=media&token=4e3d384f-32cc-4b0f-9904-ca95a42d2e44",
    "date": "2026-06-09",
    "location": null,
    "title": null,
    "caption": null,
    "rating": 5,
    "exif": {
      "aperture": "f/5.6",
      "shutter": "1s",
      "iso": 2000,
      "focalLength": "135mm",
      "camera": "SONY ILCE-6400",
      "lens": "E 18-135mm F3.5-5.6 OSS"
    },
    "edits": {
      "Contrast2012": 38,
      "Clarity2012": 6,
      "Sharpness": 40,
      "ColorNoiseReduction": 25
    }
  },
  {
    "slug": "dsc03461",
    "collections": [
      "ft-davis-2026"
    ],
    "sizeHint": "medium",
    "thumbSrc": "/thumbs/dsc03461.webp",
    "displaySrc": "/display/dsc03461.webp",
    "fullSrc": "/photos/DSC03461.jpg",
    "rawUrl": "https://firebasestorage.googleapis.com/v0/b/benwilcoxdev.firebasestorage.app/o/raw%2FDSC03461.ARW?alt=media&token=90ac2e9e-207f-4b1d-90fb-5ee733d0d863",
    "date": "2026-06-09",
    "location": null,
    "title": null,
    "caption": null,
    "rating": 5,
    "exif": {
      "aperture": "f/13",
      "shutter": "1s",
      "iso": 100,
      "focalLength": "18mm",
      "camera": "SONY ILCE-6400",
      "lens": "E 18-135mm F3.5-5.6 OSS"
    },
    "edits": {
      "Contrast2012": 44,
      "Highlights2012": -37,
      "Blacks2012": -16,
      "Sharpness": 40,
      "ColorNoiseReduction": 25
    }
  },
  {
    "slug": "dsc03482",
    "collections": [
      "ft-davis-2026"
    ],
    "sizeHint": "medium",
    "thumbSrc": "/thumbs/dsc03482.webp",
    "displaySrc": "/display/dsc03482.webp",
    "fullSrc": "/photos/DSC03482.jpg",
    "rawUrl": "https://firebasestorage.googleapis.com/v0/b/benwilcoxdev.firebasestorage.app/o/raw%2FDSC03482.ARW?alt=media&token=9963de71-b2d8-4e2f-99e2-5f441ae76c1e",
    "date": "2026-06-09",
    "location": null,
    "title": null,
    "caption": null,
    "rating": 5,
    "exif": {
      "aperture": "f/11",
      "shutter": "1s",
      "iso": 500,
      "focalLength": "70mm",
      "camera": "SONY ILCE-6400",
      "lens": "E 18-135mm F3.5-5.6 OSS"
    },
    "edits": {
      "Highlights2012": -49,
      "Whites2012": -65,
      "Blacks2012": -35,
      "Clarity2012": 6,
      "Sharpness": 40,
      "ColorNoiseReduction": 25
    }
  },
  {
    "slug": "dsc03483",
    "collections": [
      "ft-davis-2026"
    ],
    "sizeHint": "medium",
    "thumbSrc": "/thumbs/dsc03483.webp",
    "displaySrc": "/display/dsc03483.webp",
    "fullSrc": "/photos/DSC03483.jpg",
    "rawUrl": "https://firebasestorage.googleapis.com/v0/b/benwilcoxdev.firebasestorage.app/o/raw%2FDSC03483.ARW?alt=media&token=02ea0b93-9277-4153-8dca-23af0b3d5bef",
    "date": "2026-06-09",
    "location": null,
    "title": null,
    "caption": null,
    "rating": 5,
    "exif": {
      "aperture": "f/5.6",
      "shutter": "1s",
      "iso": 160,
      "focalLength": "67mm",
      "camera": "SONY ILCE-6400",
      "lens": "E 18-135mm F3.5-5.6 OSS"
    },
    "edits": {}
  },
  {
    "slug": "dsc03498",
    "collections": [
      "ft-davis-2026"
    ],
    "sizeHint": "medium",
    "thumbSrc": "/thumbs/dsc03498.webp",
    "displaySrc": "/display/dsc03498.webp",
    "fullSrc": "/photos/DSC03498.jpg",
    "rawUrl": "https://firebasestorage.googleapis.com/v0/b/benwilcoxdev.firebasestorage.app/o/raw%2FDSC03498.ARW?alt=media&token=a2da8655-a08f-40f3-a340-11d15a942463",
    "date": "2026-06-09",
    "location": null,
    "title": null,
    "caption": null,
    "rating": 5,
    "exif": {
      "aperture": "f/5",
      "shutter": "1s",
      "iso": 640,
      "focalLength": "50mm",
      "camera": "SONY ILCE-6400",
      "lens": "E 18-135mm F3.5-5.6 OSS"
    },
    "edits": {}
  },
  {
    "slug": "dsc03518",
    "collections": [
      "ft-davis-2026"
    ],
    "sizeHint": "medium",
    "thumbSrc": "/thumbs/dsc03518.webp",
    "displaySrc": "/display/dsc03518.webp",
    "fullSrc": "/photos/DSC03518.jpg",
    "rawUrl": "https://firebasestorage.googleapis.com/v0/b/benwilcoxdev.firebasestorage.app/o/raw%2FDSC03518.ARW?alt=media&token=75cee9e0-6c5e-4a62-9665-e6eef021085b",
    "date": "2026-06-09",
    "location": null,
    "title": null,
    "caption": null,
    "rating": 5,
    "exif": {
      "aperture": "f/7.1",
      "shutter": "1s",
      "iso": 100,
      "focalLength": "39mm",
      "camera": "SONY ILCE-6400",
      "lens": "E 18-135mm F3.5-5.6 OSS"
    },
    "edits": {
      "Exposure2012": 0.08,
      "Contrast2012": 7,
      "Highlights2012": -29,
      "Shadows2012": 29,
      "Whites2012": 47,
      "Blacks2012": -27,
      "Vibrance": 11,
      "Saturation": -5,
      "Sharpness": 40,
      "ColorNoiseReduction": 25
    }
  },
  {
    "slug": "dsc03526",
    "collections": [
      "uncategorized"
    ],
    "sizeHint": "medium",
    "thumbSrc": "/thumbs/dsc03526.webp",
    "displaySrc": "/display/dsc03526.webp",
    "fullSrc": "/photos/DSC03526.jpg",
    "rawUrl": null,
    "date": "2026-06-09",
    "location": null,
    "title": null,
    "caption": null,
    "rating": 5,
    "exif": {
      "aperture": "f/11",
      "shutter": "1s",
      "iso": 100,
      "focalLength": "63mm",
      "camera": "SONY ILCE-6400",
      "lens": "E 18-135mm F3.5-5.6 OSS"
    },
    "edits": null
  },
  {
    "slug": "dsc03595",
    "collections": [
      "ft-davis-2026"
    ],
    "sizeHint": "medium",
    "thumbSrc": "/thumbs/dsc03595.webp",
    "displaySrc": "/display/dsc03595.webp",
    "fullSrc": "/photos/DSC03595.jpg",
    "rawUrl": "https://firebasestorage.googleapis.com/v0/b/benwilcoxdev.firebasestorage.app/o/raw%2FDSC03595.ARW?alt=media&token=e2d02efd-dd5e-4ffb-aba5-e472df57c9cc",
    "date": "2026-06-10",
    "location": null,
    "title": null,
    "caption": null,
    "rating": 4,
    "exif": {
      "aperture": "f/9",
      "shutter": "1s",
      "iso": 12800,
      "focalLength": "53mm",
      "camera": "SONY ILCE-6400",
      "lens": "E 18-135mm F3.5-5.6 OSS"
    },
    "edits": {
      "Exposure2012": 0.41,
      "Highlights2012": -54,
      "Clarity2012": -31,
      "Vibrance": 16,
      "Saturation": 24,
      "Sharpness": 40,
      "ColorNoiseReduction": 25
    }
  },
  {
    "slug": "dsc03605",
    "collections": [
      "ft-davis-2026"
    ],
    "sizeHint": "medium",
    "thumbSrc": "/thumbs/dsc03605.webp",
    "displaySrc": "/display/dsc03605.webp",
    "fullSrc": "/photos/DSC03605.jpg",
    "rawUrl": "https://firebasestorage.googleapis.com/v0/b/benwilcoxdev.firebasestorage.app/o/raw%2FDSC03605.ARW?alt=media&token=a4073a86-cb44-47fa-a103-af95e349b1e2",
    "date": "2026-06-10",
    "location": null,
    "title": null,
    "caption": null,
    "rating": 4,
    "exif": {
      "aperture": "f/4.5",
      "shutter": "1s",
      "iso": 12800,
      "focalLength": "32mm",
      "camera": "SONY ILCE-6400",
      "lens": "E 18-135mm F3.5-5.6 OSS"
    },
    "edits": {
      "Exposure2012": 0.78,
      "Contrast2012": 9,
      "Highlights2012": 19,
      "Shadows2012": 1,
      "Whites2012": 24,
      "Blacks2012": -3,
      "Vibrance": 32,
      "Saturation": 10,
      "Sharpness": 40
    }
  },
  {
    "slug": "dsc03606",
    "collections": [
      "ft-davis-2026"
    ],
    "sizeHint": "medium",
    "thumbSrc": "/thumbs/dsc03606.webp",
    "displaySrc": "/display/dsc03606.webp",
    "fullSrc": "/photos/DSC03606.jpg",
    "rawUrl": "https://firebasestorage.googleapis.com/v0/b/benwilcoxdev.firebasestorage.app/o/raw%2FDSC03606.ARW?alt=media&token=0d6f5b48-1363-4a64-a5aa-ed66f674340c",
    "date": "2026-06-10",
    "location": null,
    "title": null,
    "caption": null,
    "rating": 4,
    "exif": {
      "aperture": "f/3.5",
      "shutter": "1s",
      "iso": 12800,
      "focalLength": "18mm",
      "camera": "SONY ILCE-6400",
      "lens": "E 18-135mm F3.5-5.6 OSS"
    },
    "edits": {
      "Exposure2012": -0.81,
      "Contrast2012": 14,
      "Highlights2012": 21,
      "Shadows2012": 51,
      "Vibrance": 23,
      "Sharpness": 40
    }
  },
  {
    "slug": "dsc03608",
    "collections": [
      "ft-davis-2026"
    ],
    "sizeHint": "medium",
    "thumbSrc": "/thumbs/dsc03608.webp",
    "displaySrc": "/display/dsc03608.webp",
    "fullSrc": "/photos/DSC03608.jpg",
    "rawUrl": "https://firebasestorage.googleapis.com/v0/b/benwilcoxdev.firebasestorage.app/o/raw%2FDSC03608.ARW?alt=media&token=db4176f2-21a6-4051-8943-555e268e79ff",
    "date": "2026-06-10",
    "location": null,
    "title": null,
    "caption": null,
    "rating": 4,
    "exif": {
      "aperture": "f/5",
      "shutter": "1s",
      "iso": 12800,
      "focalLength": "53mm",
      "camera": "SONY ILCE-6400",
      "lens": "E 18-135mm F3.5-5.6 OSS"
    },
    "edits": {
      "Exposure2012": 1.09,
      "Sharpness": 40,
      "ColorNoiseReduction": 25
    }
  },
  {
    "slug": "dsc03612",
    "collections": [
      "ft-davis-2026"
    ],
    "sizeHint": "small",
    "thumbSrc": "/thumbs/dsc03612.webp",
    "displaySrc": "/display/dsc03612.webp",
    "fullSrc": "/photos/DSC03612.jpg",
    "rawUrl": "https://firebasestorage.googleapis.com/v0/b/benwilcoxdev.firebasestorage.app/o/raw%2FDSC03612.ARW?alt=media&token=0c8245d9-ad25-400c-a112-ef6f0276d3d1",
    "date": "2026-06-10",
    "location": null,
    "title": null,
    "caption": null,
    "rating": 5,
    "exif": {
      "aperture": "f/5.6",
      "shutter": "1s",
      "iso": 12800,
      "focalLength": "69mm",
      "camera": "SONY ILCE-6400",
      "lens": "E 18-135mm F3.5-5.6 OSS"
    },
    "edits": {
      "Exposure2012": 1.35,
      "Contrast2012": 15,
      "Highlights2012": -19,
      "Whites2012": 33,
      "Blacks2012": 4,
      "Sharpness": 40
    }
  },
  {
    "slug": "dsc03640",
    "collections": [
      "ft-davis-2026"
    ],
    "sizeHint": "medium",
    "thumbSrc": "/thumbs/dsc03640.webp",
    "displaySrc": "/display/dsc03640.webp",
    "fullSrc": "/photos/DSC03640.jpg",
    "rawUrl": "https://firebasestorage.googleapis.com/v0/b/benwilcoxdev.firebasestorage.app/o/raw%2FDSC03640.ARW?alt=media&token=44e40bcb-6eb8-4862-bdff-2fc1a97e9fe2",
    "date": "2026-06-10",
    "location": null,
    "title": null,
    "caption": null,
    "rating": 4,
    "exif": {
      "aperture": "f/22",
      "shutter": "20s",
      "iso": 5000,
      "focalLength": "40mm",
      "camera": "SONY ILCE-6400",
      "lens": "E 18-135mm F3.5-5.6 OSS"
    },
    "edits": {
      "Exposure2012": 1.12,
      "Contrast2012": 29,
      "Whites2012": 34,
      "Sharpness": 40,
      "ColorNoiseReduction": 25
    }
  },
  {
    "slug": "dsc03650",
    "collections": [
      "ft-davis-2026"
    ],
    "sizeHint": "medium",
    "thumbSrc": "/thumbs/dsc03650.webp",
    "displaySrc": "/display/dsc03650.webp",
    "fullSrc": "/photos/DSC03650.jpg",
    "rawUrl": "https://firebasestorage.googleapis.com/v0/b/benwilcoxdev.firebasestorage.app/o/raw%2FDSC03650.ARW?alt=media&token=277eae4d-cd9d-4321-b6fe-2747ffd867e3",
    "date": "2026-06-10",
    "location": null,
    "title": null,
    "caption": null,
    "rating": 4,
    "exif": {
      "aperture": "f/5",
      "shutter": "30s",
      "iso": 12800,
      "focalLength": "18mm",
      "camera": "SONY ILCE-6400",
      "lens": "E 18-135mm F3.5-5.6 OSS"
    },
    "edits": {
      "Exposure2012": 0.52,
      "Contrast2012": 38,
      "Shadows2012": -55,
      "Blacks2012": -31,
      "Sharpness": 40,
      "ColorNoiseReduction": 25
    }
  },
  {
    "slug": "dsc03666",
    "collections": [
      "ft-davis-2026"
    ],
    "sizeHint": "small",
    "thumbSrc": "/thumbs/dsc03666.webp",
    "displaySrc": "/display/dsc03666.webp",
    "fullSrc": "/photos/DSC03666.jpg",
    "rawUrl": "https://firebasestorage.googleapis.com/v0/b/benwilcoxdev.firebasestorage.app/o/raw%2FDSC03666.ARW?alt=media&token=5bcbf26f-cf17-4764-a414-b91cc64c0cd1",
    "date": "2026-06-10",
    "location": null,
    "title": null,
    "caption": null,
    "rating": 5,
    "exif": {
      "aperture": "f/3.5",
      "shutter": "30s",
      "iso": 12800,
      "focalLength": "18mm",
      "camera": "SONY ILCE-6400",
      "lens": "E 18-135mm F3.5-5.6 OSS"
    },
    "edits": {
      "Exposure2012": 0.19,
      "Contrast2012": 32,
      "Highlights2012": -33,
      "Whites2012": 53,
      "Sharpness": 40,
      "ColorNoiseReduction": 25
    }
  },
  {
    "slug": "dsc03740",
    "collections": [
      "bluehole-june-2026"
    ],
    "sizeHint": "medium",
    "thumbSrc": "/thumbs/dsc03740.webp",
    "displaySrc": "/display/dsc03740.webp",
    "fullSrc": "/photos/DSC03740.jpg",
    "rawUrl": "https://firebasestorage.googleapis.com/v0/b/benwilcoxdev.firebasestorage.app/o/raw%2FDSC03740.ARW?alt=media&token=a9fe50e1-91b2-4f76-9061-5da412a83b1a",
    "date": "2026-06-12",
    "location": null,
    "title": null,
    "caption": null,
    "rating": 4,
    "exif": {
      "aperture": "f/5",
      "shutter": "1s",
      "iso": 100,
      "focalLength": "45mm",
      "camera": "SONY ILCE-6400",
      "lens": "E 18-135mm F3.5-5.6 OSS"
    },
    "edits": {
      "Exposure2012": 0.16,
      "Contrast2012": 28,
      "Highlights2012": -29,
      "Shadows2012": 2,
      "Whites2012": -70,
      "Blacks2012": -11,
      "Clarity2012": 23,
      "Sharpness": 40,
      "ColorNoiseReduction": 25
    }
  },
  {
    "slug": "dsc03742",
    "collections": [
      "bluehole-june-2026"
    ],
    "sizeHint": "medium",
    "thumbSrc": "/thumbs/dsc03742.webp",
    "displaySrc": "/display/dsc03742.webp",
    "fullSrc": "/photos/DSC03742.jpg",
    "rawUrl": "https://firebasestorage.googleapis.com/v0/b/benwilcoxdev.firebasestorage.app/o/raw%2FDSC03742.ARW?alt=media&token=f63fba13-7101-4dfe-8e66-5d84c85db46e",
    "date": "2026-06-12",
    "location": null,
    "title": null,
    "caption": null,
    "rating": 4,
    "exif": {
      "aperture": "f/5",
      "shutter": "1s",
      "iso": 100,
      "focalLength": "45mm",
      "camera": "SONY ILCE-6400",
      "lens": "E 18-135mm F3.5-5.6 OSS"
    },
    "edits": {
      "Exposure2012": 0.46,
      "Contrast2012": 10,
      "Highlights2012": -88,
      "Shadows2012": 3,
      "Whites2012": -28,
      "Blacks2012": 35,
      "Clarity2012": 10,
      "Sharpness": 40,
      "ColorNoiseReduction": 25
    }
  },
  {
    "slug": "dsc03762",
    "collections": [
      "bluehole-june-2026"
    ],
    "sizeHint": "medium",
    "thumbSrc": "/thumbs/dsc03762.webp",
    "displaySrc": "/display/dsc03762.webp",
    "fullSrc": "/photos/DSC03762.jpg",
    "rawUrl": "https://firebasestorage.googleapis.com/v0/b/benwilcoxdev.firebasestorage.app/o/raw%2FDSC03762.ARW?alt=media&token=383fc4b4-1133-47d0-9f64-3098e7162216",
    "date": "2026-06-12",
    "location": null,
    "title": null,
    "caption": null,
    "rating": 4,
    "exif": {
      "aperture": "f/22",
      "shutter": "1s",
      "iso": 12800,
      "focalLength": "135mm",
      "camera": "SONY ILCE-6400",
      "lens": "E 18-135mm F3.5-5.6 OSS"
    },
    "edits": {
      "Exposure2012": 0.74,
      "Sharpness": 40,
      "ColorNoiseReduction": 25
    }
  },
  {
    "slug": "dsc03768",
    "collections": [
      "bluehole-june-2026"
    ],
    "sizeHint": "medium",
    "thumbSrc": "/thumbs/dsc03768.webp",
    "displaySrc": "/display/dsc03768.webp",
    "fullSrc": "/photos/DSC03768.jpg",
    "rawUrl": "https://firebasestorage.googleapis.com/v0/b/benwilcoxdev.firebasestorage.app/o/raw%2FDSC03768.ARW?alt=media&token=c8fd086b-2eb9-41d7-831f-824e6cba4d54",
    "date": "2026-06-12",
    "location": null,
    "title": null,
    "caption": null,
    "rating": 4,
    "exif": {
      "aperture": "f/22",
      "shutter": "1s",
      "iso": 6400,
      "focalLength": "88mm",
      "camera": "SONY ILCE-6400",
      "lens": "E 18-135mm F3.5-5.6 OSS"
    },
    "edits": {
      "Exposure2012": -0.09,
      "Highlights2012": -59,
      "Shadows2012": 75,
      "Whites2012": 29,
      "Blacks2012": 94,
      "Sharpness": 40,
      "ColorNoiseReduction": 25
    }
  },
  {
    "slug": "dsc03772",
    "collections": [
      "bluehole-june-2026"
    ],
    "sizeHint": "medium",
    "thumbSrc": "/thumbs/dsc03772.webp",
    "displaySrc": "/display/dsc03772.webp",
    "fullSrc": "/photos/DSC03772.jpg",
    "rawUrl": "https://firebasestorage.googleapis.com/v0/b/benwilcoxdev.firebasestorage.app/o/raw%2FDSC03772.ARW?alt=media&token=279ed17c-0efd-4f43-ac2a-b2f099dcec27",
    "date": "2026-06-12",
    "location": null,
    "title": null,
    "caption": null,
    "rating": 5,
    "exif": {
      "aperture": "f/5.6",
      "shutter": "1s",
      "iso": 400,
      "focalLength": "97mm",
      "camera": "SONY ILCE-6400",
      "lens": "E 18-135mm F3.5-5.6 OSS"
    },
    "edits": {
      "Exposure2012": 0.24,
      "Contrast2012": 16,
      "Highlights2012": -22,
      "Shadows2012": 24,
      "Whites2012": -45,
      "Blacks2012": -8,
      "Clarity2012": 19,
      "Vibrance": 24,
      "Saturation": 6,
      "Sharpness": 40,
      "ColorNoiseReduction": 25
    }
  },
  {
    "slug": "dsc03775",
    "collections": [
      "bluehole-june-2026"
    ],
    "sizeHint": "medium",
    "thumbSrc": "/thumbs/dsc03775.webp",
    "displaySrc": "/display/dsc03775.webp",
    "fullSrc": "/photos/DSC03775.jpg",
    "rawUrl": "https://firebasestorage.googleapis.com/v0/b/benwilcoxdev.firebasestorage.app/o/raw%2FDSC03775.ARW?alt=media&token=fd88eef2-e523-430b-9336-053bfc586dfd",
    "date": "2026-06-12",
    "location": null,
    "title": null,
    "caption": null,
    "rating": 4,
    "exif": {
      "aperture": "f/5.6",
      "shutter": "1s",
      "iso": 320,
      "focalLength": "56mm",
      "camera": "SONY ILCE-6400",
      "lens": "E 18-135mm F3.5-5.6 OSS"
    },
    "edits": {
      "Exposure2012": 0.16,
      "Contrast2012": 28,
      "Highlights2012": -29,
      "Shadows2012": 2,
      "Whites2012": -70,
      "Blacks2012": -11,
      "Clarity2012": 23,
      "Sharpness": 40,
      "ColorNoiseReduction": 25
    }
  },
  {
    "slug": "dsc03801",
    "collections": [
      "bluehole-june-2026"
    ],
    "sizeHint": "medium",
    "thumbSrc": "/thumbs/dsc03801.webp",
    "displaySrc": "/display/dsc03801.webp",
    "fullSrc": "/photos/DSC03801.jpg",
    "rawUrl": "https://firebasestorage.googleapis.com/v0/b/benwilcoxdev.firebasestorage.app/o/raw%2FDSC03801.ARW?alt=media&token=369743eb-92cc-4331-ae66-5227db29a0a5",
    "date": "2026-06-12",
    "location": null,
    "title": null,
    "caption": null,
    "rating": 4,
    "exif": {
      "aperture": "f/4.5",
      "shutter": "1s",
      "iso": 250,
      "focalLength": "31mm",
      "camera": "SONY ILCE-6400",
      "lens": "E 18-135mm F3.5-5.6 OSS"
    },
    "edits": {
      "Exposure2012": 0.16,
      "Highlights2012": -29,
      "Shadows2012": 2,
      "Whites2012": -70,
      "Blacks2012": -11,
      "Clarity2012": 23,
      "Sharpness": 40,
      "ColorNoiseReduction": 25
    }
  },
  {
    "slug": "dsc03829",
    "collections": [
      "austin-june-2026"
    ],
    "sizeHint": "medium",
    "thumbSrc": "/thumbs/dsc03829.webp",
    "displaySrc": "/display/dsc03829.webp",
    "fullSrc": "/photos/DSC03829.jpg",
    "rawUrl": "https://firebasestorage.googleapis.com/v0/b/benwilcoxdev.firebasestorage.app/o/raw%2FDSC03829.ARW?alt=media&token=de97db4a-a196-4945-997e-d4c39a2d03b6",
    "date": "2026-06-16",
    "location": null,
    "title": null,
    "caption": null,
    "rating": 4,
    "exif": {
      "aperture": "f/4.5",
      "shutter": "1s",
      "iso": 100,
      "focalLength": "27mm",
      "camera": "SONY ILCE-6400",
      "lens": "E 18-135mm F3.5-5.6 OSS"
    },
    "edits": {
      "Exposure2012": 0.5,
      "Contrast2012": 16,
      "Vibrance": 11,
      "Saturation": 8,
      "Sharpness": 40,
      "ColorNoiseReduction": 25
    }
  },
  {
    "slug": "dsc03839",
    "collections": [
      "austin-june-2026"
    ],
    "sizeHint": "medium",
    "thumbSrc": "/thumbs/dsc03839.webp",
    "displaySrc": "/display/dsc03839.webp",
    "fullSrc": "/photos/DSC03839.jpg",
    "rawUrl": "https://firebasestorage.googleapis.com/v0/b/benwilcoxdev.firebasestorage.app/o/raw%2FDSC03839.ARW?alt=media&token=b7e2dc5e-1b5a-4e05-8478-c56e7b0aea44",
    "date": "2026-06-16",
    "location": null,
    "title": null,
    "caption": null,
    "rating": 4,
    "exif": {
      "aperture": "f/14",
      "shutter": "1s",
      "iso": 12800,
      "focalLength": "60mm",
      "camera": "SONY ILCE-6400",
      "lens": "E 18-135mm F3.5-5.6 OSS"
    },
    "edits": {
      "Exposure2012": 0.16,
      "Contrast2012": 28,
      "Highlights2012": -29,
      "Shadows2012": 2,
      "Whites2012": -70,
      "Blacks2012": -11,
      "Clarity2012": 23,
      "Sharpness": 40,
      "ColorNoiseReduction": 25
    }
  },
  {
    "slug": "dsc03846",
    "collections": [
      "austin-june-2026"
    ],
    "sizeHint": "medium",
    "thumbSrc": "/thumbs/dsc03846.webp",
    "displaySrc": "/display/dsc03846.webp",
    "fullSrc": "/photos/DSC03846.jpg",
    "rawUrl": "https://firebasestorage.googleapis.com/v0/b/benwilcoxdev.firebasestorage.app/o/raw%2FDSC03846.ARW?alt=media&token=83e969ae-c525-4f50-a7ee-35350d98d0a8",
    "date": "2026-06-16",
    "location": null,
    "title": "H",
    "caption": null,
    "rating": 2,
    "exif": {
      "aperture": "f/5",
      "shutter": "1s",
      "iso": 1000,
      "focalLength": "53mm",
      "camera": "SONY ILCE-6400",
      "lens": "E 18-135mm F3.5-5.6 OSS"
    },
    "edits": {
      "Exposure2012": 1.36,
      "Contrast2012": 28,
      "Highlights2012": -29,
      "Shadows2012": 2,
      "Whites2012": -70,
      "Blacks2012": -11,
      "Clarity2012": 23,
      "Sharpness": 40,
      "ColorNoiseReduction": 25
    }
  },
  {
    "slug": "dsc03847",
    "collections": [
      "austin-june-2026"
    ],
    "sizeHint": "medium",
    "thumbSrc": "/thumbs/dsc03847.webp",
    "displaySrc": "/display/dsc03847.webp",
    "fullSrc": "/photos/DSC03847.jpg",
    "rawUrl": "https://firebasestorage.googleapis.com/v0/b/benwilcoxdev.firebasestorage.app/o/raw%2FDSC03847.ARW?alt=media&token=a0b37626-0b9e-4f30-973e-f66b81bf9ef3",
    "date": "2026-06-16",
    "location": null,
    "title": null,
    "caption": null,
    "rating": 4,
    "exif": {
      "aperture": "f/5",
      "shutter": "1s",
      "iso": 12800,
      "focalLength": "50mm",
      "camera": "SONY ILCE-6400",
      "lens": "E 18-135mm F3.5-5.6 OSS"
    },
    "edits": {
      "Exposure2012": 0.16,
      "Contrast2012": 20,
      "Highlights2012": -29,
      "Shadows2012": 2,
      "Blacks2012": -11,
      "Sharpness": 40,
      "ColorNoiseReduction": 25
    }
  },
  {
    "slug": "dsc03850",
    "collections": [
      "austin-june-2026"
    ],
    "sizeHint": "medium",
    "thumbSrc": "/thumbs/dsc03850.webp",
    "displaySrc": "/display/dsc03850.webp",
    "fullSrc": "/photos/DSC03850.jpg",
    "rawUrl": "https://firebasestorage.googleapis.com/v0/b/benwilcoxdev.firebasestorage.app/o/raw%2FDSC03850.ARW?alt=media&token=9215e169-1da8-4e3f-8169-ea9e21634958",
    "date": "2026-06-16",
    "location": null,
    "title": null,
    "caption": null,
    "rating": 4,
    "exif": {
      "aperture": "f/5",
      "shutter": "1s",
      "iso": 5000,
      "focalLength": "43mm",
      "camera": "SONY ILCE-6400",
      "lens": "E 18-135mm F3.5-5.6 OSS"
    },
    "edits": {
      "Exposure2012": 0.67,
      "Contrast2012": 26,
      "Clarity2012": -32,
      "Vibrance": 13,
      "Saturation": 6,
      "Sharpness": 40,
      "ColorNoiseReduction": 25
    }
  },
  {
    "slug": "dsc03855",
    "collections": [
      "austin-june-2026"
    ],
    "sizeHint": "medium",
    "thumbSrc": "/thumbs/dsc03855.webp",
    "displaySrc": "/display/dsc03855.webp",
    "fullSrc": "/photos/DSC03855.jpg",
    "rawUrl": "https://firebasestorage.googleapis.com/v0/b/benwilcoxdev.firebasestorage.app/o/raw%2FDSC03855.ARW?alt=media&token=59f4ecb5-e477-43f4-9271-2591d5e5adf9",
    "date": "2026-06-16",
    "location": null,
    "title": null,
    "caption": null,
    "rating": 4,
    "exif": {
      "aperture": "f/5.6",
      "shutter": "1s",
      "iso": 2000,
      "focalLength": "64mm",
      "camera": "SONY ILCE-6400",
      "lens": "E 18-135mm F3.5-5.6 OSS"
    },
    "edits": {
      "Exposure2012": 0.67,
      "Contrast2012": 26,
      "Clarity2012": -32,
      "Vibrance": 16,
      "Saturation": -19,
      "Sharpness": 40,
      "ColorNoiseReduction": 25
    }
  },
  {
    "slug": "dsc03859",
    "collections": [
      "austin-june-2026",
      "buildings"
    ],
    "sizeHint": "small",
    "thumbSrc": "/thumbs/dsc03859.webp",
    "displaySrc": "/display/dsc03859.webp",
    "fullSrc": "/photos/DSC03859.jpg",
    "rawUrl": "https://firebasestorage.googleapis.com/v0/b/benwilcoxdev.firebasestorage.app/o/raw%2FDSC03859.ARW?alt=media&token=701fada9-9aeb-4c7d-adfd-5af1fbec3df3",
    "date": "2026-06-16",
    "location": null,
    "title": null,
    "caption": null,
    "rating": 3,
    "exif": {
      "aperture": "f/5.6",
      "shutter": "1s",
      "iso": 1250,
      "focalLength": "61mm",
      "camera": "SONY ILCE-6400",
      "lens": "E 18-135mm F3.5-5.6 OSS"
    },
    "edits": {
      "Exposure2012": 0.67,
      "Contrast2012": 26,
      "Clarity2012": -32,
      "Vibrance": 16,
      "Saturation": -19,
      "Sharpness": 40,
      "ColorNoiseReduction": 25
    }
  },
  {
    "slug": "dsc03860",
    "collections": [
      "austin-june-2026"
    ],
    "sizeHint": "large",
    "thumbSrc": "/thumbs/dsc03860.webp",
    "displaySrc": "/display/dsc03860.webp",
    "fullSrc": "/photos/DSC03860.jpg",
    "rawUrl": "https://firebasestorage.googleapis.com/v0/b/benwilcoxdev.firebasestorage.app/o/raw%2FDSC03860.ARW?alt=media&token=df5692ab-6e75-4b6b-8328-f989d6439056",
    "date": "2026-06-16",
    "location": null,
    "title": "Bench",
    "caption": null,
    "rating": 4,
    "exif": {
      "aperture": "f/5",
      "shutter": "1s",
      "iso": 12800,
      "focalLength": "50mm",
      "camera": "SONY ILCE-6400",
      "lens": "E 18-135mm F3.5-5.6 OSS"
    },
    "edits": {}
  },
  {
    "slug": "dsc03865",
    "collections": [
      "austin-june-2026"
    ],
    "sizeHint": "large",
    "thumbSrc": "/thumbs/dsc03865.webp",
    "displaySrc": "/display/dsc03865.webp",
    "fullSrc": "/photos/DSC03865.jpg",
    "rawUrl": "https://firebasestorage.googleapis.com/v0/b/benwilcoxdev.firebasestorage.app/o/raw%2FDSC03865.ARW?alt=media&token=ec9058c5-6f23-4b7e-b5ee-0d2096544504",
    "date": "2026-06-16",
    "location": null,
    "title": "THIS IS THE TITLE",
    "caption": "THIS IS THE CAPTION",
    "rating": 4,
    "exif": {
      "aperture": "f/5.6",
      "shutter": "1s",
      "iso": 12800,
      "focalLength": "66mm",
      "camera": "SONY ILCE-6400",
      "lens": "E 18-135mm F3.5-5.6 OSS"
    },
    "edits": {
      "Sharpness": 40,
      "ColorNoiseReduction": 25
    }
  },
]
