import { ExifTool } from 'exiftool-vendored'
import { readFileSync, writeFileSync, existsSync, readdirSync } from 'fs'
import { join, basename, extname } from 'path'
import type { Photo, SizeHint } from '../src/types/photos'

const PHOTOS_DIR = join(import.meta.dirname, '../public/photos')
const OUTPUT_FILE = join(import.meta.dirname, '../src/content/photos.ts')
const OVERRIDES_FILE = join(import.meta.dirname, '../photos.overrides.json')

const XMP_KEYS = [
  'Exposure2012',
  'Contrast2012',
  'Highlights2012',
  'Shadows2012',
  'Whites2012',
  'Blacks2012',
  'Clarity2012',
  'Vibrance',
  'Saturation',
  'Sharpness',
  'LuminanceSmoothing',
  'ColorNoiseReduction',
]

function deriveSlug(filename: string): string {
  return basename(filename, extname(filename))
    .toLowerCase()
    .replace(/[\s_]+/g, '-')
    .replace(/[^a-z0-9-]/g, '')
}

function formatAperture(value: number | string | undefined): string | null {
  if (value == null) return null
  const num = typeof value === 'string' ? parseFloat(value) : value
  if (isNaN(num)) return null
  return `f/${num.toFixed(1).replace(/\.0$/, '')}`
}

function formatShutter(value: number | string | undefined): string | null {
  if (value == null) return null
  const num = typeof value === 'string' ? parseFloat(value) : value
  if (isNaN(num)) return null
  if (num >= 1) return `${num}s`
  const denom = Math.round(1 / num)
  return `1/${denom}s`
}

function formatFocalLength(value: number | string | undefined): string | null {
  if (value == null) return null
  const num = typeof value === 'string' ? parseFloat(value) : value
  if (isNaN(num)) return null
  return `${Math.round(num)}mm`
}

function parseXmp(xmpPath: string): Record<string, number> | null {
  if (!existsSync(xmpPath)) return null
  const content = readFileSync(xmpPath, 'utf-8')
  const edits: Record<string, number> = {}
  for (const key of XMP_KEYS) {
    const match = content.match(new RegExp(`crs:${key}="([^"]+)"`))
    if (match) {
      const val = parseFloat(match[1])
      if (!isNaN(val) && val !== 0) {
        edits[key] = val
      }
    }
  }
  return edits
}

async function main() {
  const exiftool = new ExifTool()

  const overrides: Record<string, Partial<Photo>> = existsSync(OVERRIDES_FILE)
    ? JSON.parse(readFileSync(OVERRIDES_FILE, 'utf-8'))
    : {}

  const allFiles = readdirSync(PHOTOS_DIR)
  const imageFiles = allFiles.filter(f => /\.(jpg|jpeg|png)$/i.test(f))

  const photos: Photo[] = []

  for (const file of imageFiles) {
    const filePath = join(PHOTOS_DIR, file)
    const slug = deriveSlug(file)

    const tags = await exiftool.read(filePath)

    const width = (tags.ImageWidth as number | undefined) ?? 0
    const height = (tags.ImageHeight as number | undefined) ?? 0

    const aperture = formatAperture((tags.Aperture ?? tags.FNumber) as number | undefined)
    const shutter = formatShutter((tags.ShutterSpeed ?? tags.ExposureTime) as number | undefined)
    const iso = (tags.ISO as number | undefined) ?? null
    const focalLength = formatFocalLength((tags.FocalLength as string | number | undefined))
    const make = (tags.Make as string | undefined) ?? ''
    const model = (tags.Model as string | undefined) ?? ''
    const camera = make || model ? `${make} ${model}`.trim() : null
    const lens = (tags.LensModel ?? tags.LensInfo) as string | undefined ?? null

    const rawDate = tags.DateTimeOriginal ?? tags.CreateDate
    let date: string | null = null
    if (rawDate) {
      const d = rawDate instanceof Date ? rawDate : new Date(String(rawDate))
      if (!isNaN(d.getTime())) {
        date = d.toISOString().slice(0, 10)
      }
    }

    const xmpName = allFiles.find(f => f.toLowerCase() === basename(file, extname(file)).toLowerCase() + '.xmp')
    const xmpPath = xmpName ? join(PHOTOS_DIR, xmpName) : null
    const edits = xmpPath ? parseXmp(xmpPath) : null

    const defaultSizeHint: SizeHint = width > height ? 'medium' : 'small'

    const base: Photo = {
      slug,
      collections: ['street'],
      sizeHint: defaultSizeHint,
      displaySrc: `/photos/${file}`,
      rawUrl: null,
      date,
      location: null,
      exif: {
        aperture,
        shutter,
        iso,
        focalLength,
        camera,
        lens: lens as string | null,
      },
      edits,
    }

    const override = overrides[slug] ?? {}
    photos.push({ ...base, ...override })
  }

  photos.sort((a, b) => {
    if (!a.date && !b.date) return 0
    if (!a.date) return 1
    if (!b.date) return -1
    return a.date.localeCompare(b.date)
  })

  const lines: string[] = []
  lines.push('// AUTO-GENERATED by scripts/generate-photos.ts — do not edit by hand')
  lines.push("import type { Photo } from '../types/photos'")
  lines.push('')
  lines.push('export const photos: Photo[] = [')
  for (const photo of photos) {
    lines.push('  ' + JSON.stringify(photo, null, 2).replace(/\n/g, '\n  ') + ',')
  }
  lines.push(']')
  lines.push('')

  writeFileSync(OUTPUT_FILE, lines.join('\n'))
  console.log(`Generated ${photos.length} photos → src/content/photos.ts`)

  await exiftool.end()
}

main().catch(err => {
  console.error(err)
  process.exit(1)
})
